/**
 * Pkg121: Text / Byte Streams over LiveKit
 *
 * Thin scope/id-keyed wrapper around livekit-client's text + byte stream APIs:
 *   - localParticipant.sendText / streamText
 *   - localParticipant.sendFile / streamBytes
 *   - room.registerTextStreamHandler / registerByteStreamHandler
 *
 * Use cases:
 *   - Chunked transfer of large chat messages (>1KB) without DataPacket size cap
 *   - File attachments (images, voice notes, docs) up to multi-GB
 *   - Streaming AI/transcription output progressively to the UI
 *
 * - NO Supabase Realtime channels, NO polls, NO cross-user DB reads.
 * - Money/audit/persistence still goes through Supabase RPC first; this is
 *   the *transport* only — receivers may persist via separate RPC.
 * - Kill-switch: app_settings.livekit_signaling_enabled.streams (default ON;
 *   admin can flip false to disable globally).
 */
import type { Room } from 'livekit-client';
import { isLiveKitEnabled } from './livekitSignaling';
import {
  trySendNativeText,
  tryRegisterNativeTextStreamHandler,
  tryUnregisterNativeTextStreamHandler,
} from './livekitNativeMessaging';

export type StreamScope = 'call' | 'live' | 'party';

interface RegEntry {
  room: Room;
  textTopics: Set<string>;
  byteTopics: Set<string>;
}

const registry = new Map<string, RegEntry>();
const key = (scope: StreamScope, id: string) => `${scope}:${id}`;

export function registerStreamRoom(scope: StreamScope, id: string, room: Room) {
  if (!room) return;
  const k = key(scope, id);
  const existing = registry.get(k);
  if (existing && existing.room === room) return;
  if (existing && existing.room !== room) {
    try {
      existing.textTopics.forEach((t) => existing.room.unregisterTextStreamHandler?.(t));
      existing.byteTopics.forEach((t) => existing.room.unregisterByteStreamHandler?.(t));
    } catch {
      /* ignore */
    }
  }
  registry.set(k, { room, textTopics: new Set(), byteTopics: new Set() });

  // Pkg201 — auto-attach iOS Safari audio-playback unlock watcher.
  // Dynamic import avoids a circular import (livekitAudioUnlock imports this file).
  void import('./livekitAudioUnlock')
    .then((mod) => {
      try {
        mod.startAudioUnlockWatcher(scope, id);
      } catch {
        /* ignore */
      }
    })
    .catch(() => {
      /* ignore */
    });

  // Pkg202 — auto-attach disconnect-reason watcher (M5).
  void import('./livekitDisconnectReason')
    .then((mod) => {
      try {
        mod.startDisconnectReasonWatcher(scope, id);
      } catch {
        /* ignore */
      }
    })
    .catch(() => {
      /* ignore */
    });
}

export function unregisterStreamRoom(scope: StreamScope, id: string) {
  const k = key(scope, id);
  const entry = registry.get(k);
  if (!entry) return;
  try {
    entry.textTopics.forEach((t) => entry.room.unregisterTextStreamHandler?.(t));
    entry.byteTopics.forEach((t) => entry.room.unregisterByteStreamHandler?.(t));
  } catch {
    /* ignore */
  }
  registry.delete(k);

  // Pkg201 — tear down audio-unlock watcher for this room.
  void import('./livekitAudioUnlock')
    .then((mod) => {
      try {
        mod.stopAudioUnlockWatcher(scope, id);
      } catch {
        /* ignore */
      }
    })
    .catch(() => {
      /* ignore */
    });

  // Pkg202 — tear down disconnect-reason watcher (M5).
  void import('./livekitDisconnectReason')
    .then((mod) => {
      try {
        mod.stopDisconnectReasonWatcher(scope, id);
      } catch {
        /* ignore */
      }
    })
    .catch(() => {
      /* ignore */
    });
}

/**
 * Internal — get the Room registered for a scope/id. Used by sibling modules
 * (e.g. livekitParticipantAttributes) so they don't need their own registry.
 * Returns null when no room is registered yet.
 */
export function _getRegisteredRoom(scope: StreamScope, id: string): Room | null {
  return registry.get(key(scope, id))?.room ?? null;
}

/**
 * Phase-3 C4: force-disconnect every registered Room.
 * Called from CallProvider before accepting a private call so the prior
 * live-stream / party-room LiveKit session releases mic/camera before
 * the private call takes over.  Ignores non-connected rooms and swallows
 * errors so a single bad room cannot block call acceptance.
 */
export function disconnectAllRegisteredRooms() {
  registry.forEach((entry) => {
    try {
      const s = (entry.room as any).state;
      if (s === 'connected' || s === 'reconnecting') {
        entry.room.disconnect(true);
      }
    } catch {
      /* ignore — room may already be tearing down */
    }
  });
}


// ─── Text streams ─────────────────────────────────────────────────────────

export interface TextStreamInfo {
  /** Stream id (generated by LiveKit). */
  id: string;
  /** Topic the sender used. */
  topic: string;
  /** Sender's participant identity (server-trusted). */
  senderIdentity: string;
  /** Optional attached metadata string from the sender. */
  attachedStreamIds?: string[];
  /** Sender's `name` field. */
  mimeType?: string;
  /** Total expected size in bytes (may be undefined for open-ended streams). */
  size?: number;
  /** Arbitrary string attributes from sender. */
  attributes?: Record<string, string>;
  /** Timestamp from sender. */
  timestamp?: number;
}

export interface TextStreamHandlerContext {
  info: TextStreamInfo;
  /** Full text payload (reader is fully drained before handler resolves). */
  text: string;
}

/**
 * Register a handler for an incoming text stream topic.
 * Returns an unregister function — call on component unmount.
 */
export function registerTextStreamHandler(
  scope: StreamScope,
  id: string,
  topic: string,
  handler: (ctx: TextStreamHandlerContext) => void | Promise<void>,
): () => void {
  const entry = registry.get(key(scope, id));
  let nativeRegistered = false;

  // Native fallback: register a parallel handler so pure-native Android
  // sessions (no JS Room) still surface incoming text streams. No-op on web.
  void tryRegisterNativeTextStreamHandler(topic, {
    onComplete: async (e) => {
      const enabled = await isLiveKitEnabled('streams');
      if (!enabled) return;
      try {
        const info: TextStreamInfo = {
          id: e.streamId,
          topic,
          senderIdentity: e.fromIdentity,
          attributes: e.attributes,
        };
        await handler({ info, text: e.text ?? '' });
      } catch (err) {
        console.warn(`[Pkg121-native] text stream handler(${topic}) failed`, err);
      }
    },
  }).then((ok) => { nativeRegistered = ok; });

  if (!entry) {
    // Pure native session — only the native handler installed above.
    return () => {
      if (nativeRegistered) void tryUnregisterNativeTextStreamHandler(topic);
    };
  }

  try {
    entry.room.registerTextStreamHandler(topic, async (reader: any, participantInfo: any) => {
      const enabled = await isLiveKitEnabled('streams');
      if (!enabled) return;
      try {
        const text: string = typeof reader.readAll === 'function'
          ? await reader.readAll()
          : await drainAsyncIterableText(reader);
        const info: TextStreamInfo = {
          topic: reader.info?.topic ?? topic,
          attachedStreamIds: reader.info?.attachedStreamIds,
          mimeType: reader.info?.mimeType,
          size: reader.info?.size,
          timestamp: reader.info?.timestamp,
        };
        await handler({ info, text });
      } catch (err) {
        console.warn(`[Pkg121] text stream handler(${topic}) failed`, err);
      }
    });
    entry.textTopics.add(topic);
  } catch (err) {
    console.warn(`[Pkg121] registerTextStreamHandler(${topic}) failed`, err);
  }
  return () => {
    try {
      entry.room.unregisterTextStreamHandler?.(topic);
    } catch {
      /* ignore */
    }
    entry.textTopics.delete(topic);
    if (nativeRegistered) void tryUnregisterNativeTextStreamHandler(topic);
  };
}

export interface SendTextOptions {
  topic: string;
  /** Optional list of recipient identities; default = all participants. */
  destinationIdentities?: string[];
  attributes?: Record<string, string>;
}

/** One-shot text send (no progress). */
export async function sendText(
  scope: StreamScope,
  id: string,
  text: string,
  opts: SendTextOptions,
): Promise<{ id: string } | null> {
  const enabled = await isLiveKitEnabled('streams');
  if (!enabled) throw new Error('streams_disabled');
  const entry = registry.get(key(scope, id));
  if (!entry) {
    // Pure native fallback (no JS Room).
    const sent = await trySendNativeText({
      text,
      topic: opts.topic,
      destinationIdentities: opts.destinationIdentities,
    });
    if (!sent) throw new Error('room_not_registered');
    return null;
  }
  const info = await entry.room.localParticipant.sendText(text, {
    attributes: opts.attributes,
  } as any);
  return info ? { id: (info as any).id } : null;
}

// ─── Byte / file streams ──────────────────────────────────────────────────

export interface ByteStreamInfo {
  id: string;
  topic: string;
  senderIdentity: string;
  mimeType?: string;
  name?: string;
  size?: number;
  attributes?: Record<string, string>;
  timestamp?: number;
}

export interface ByteStreamHandlerContext {
  info: ByteStreamInfo;
  /** Concatenated payload (reader is fully drained). */
  bytes: Uint8Array;
}

export function registerByteStreamHandler(
  scope: StreamScope,
  id: string,
  topic: string,
  handler: (ctx: ByteStreamHandlerContext) => void | Promise<void>,
): () => void {
  const entry = registry.get(key(scope, id));
  if (!entry) {
    console.warn(`[Pkg121] registerByteStreamHandler: Room not registered for ${scope}:${id}`);
    return () => {};
  }
  try {
    entry.room.registerByteStreamHandler(topic, async (reader: any, participantInfo: any) => {
      const enabled = await isLiveKitEnabled('streams');
      if (!enabled) return;
      try {
        const chunks: Uint8Array[] = [];
        if (typeof reader.readAll === 'function') {
          const all = await reader.readAll();
          chunks.push(all instanceof Uint8Array ? all : new Uint8Array(all));
        } else {
          for await (const chunk of reader as AsyncIterable<Uint8Array>) {
            chunks.push(chunk);
          }
        }
        const total = chunks.reduce((s, c) => s + c.byteLength, 0);
        const bytes = new Uint8Array(total);
        let offset = 0;
        for (const c of chunks) {
          bytes.set(c, offset);
          offset += c.byteLength;
        }
        const info: ByteStreamInfo = {
          id: reader.info?.id ?? '',
          topic: reader.info?.topic ?? topic,
          senderIdentity: participantInfo?.identity ?? '',
          mimeType: reader.info?.mimeType,
          name: reader.info?.name,
          size: reader.info?.size,
          attributes: reader.info?.attributes,
          timestamp: reader.info?.timestamp,
        };
        await handler({ info, bytes });
      } catch (err) {
        console.warn(`[Pkg121] byte stream handler(${topic}) failed`, err);
      }
    });
    entry.byteTopics.add(topic);
  } catch (err) {
    console.warn(`[Pkg121] registerByteStreamHandler(${topic}) failed`, err);
  }
  return () => {
    try {
      entry.room.unregisterByteStreamHandler?.(topic);
    } catch {
      /* ignore */
    }
    entry.byteTopics.delete(topic);
  };
}

export interface SendFileOptions {
  topic: string;
  destinationIdentities?: string[];
  /** Override file name (defaults to file.name). */
  name?: string;
  /** Override MIME type (defaults to file.type). */
  mimeType?: string;
  attributes?: Record<string, string>;
  /** Optional per-chunk progress callback (0..1). */
  onProgress?: (progress: number) => void;
}

export async function sendFile(
  scope: StreamScope,
  id: string,
  file: File | Blob,
  opts: SendFileOptions,
): Promise<{ id: string } | null> {
  const enabled = await isLiveKitEnabled('streams');
  if (!enabled) throw new Error('streams_disabled');
  const entry = registry.get(key(scope, id));
  if (!entry) throw new Error('room_not_registered');
  const info = await entry.room.localParticipant.sendFile(file as File, {
    topic: opts.topic,
    destinationIdentities: opts.destinationIdentities,
    name: opts.name,
    mimeType: opts.mimeType,
    attributes: opts.attributes,
    onProgress: opts.onProgress,
  } as any);
  return info ? { id: (info as any).id } : null;
}

// ─── Pkg191 — Streaming writers (Datastream API, Item #3) ─────────────────
//
// `sendText` / `sendFile` are one-shot buffered helpers. For unbounded /
// incremental payloads (LLM token-by-token transcripts, large file uploads
// with backpressure, live captions, partial AI replies) use the writer-based
// `streamText` / `streamBytes` APIs. They return a Writer with `.write(chunk)`
// and `.close()` so the caller controls pacing.
//
// Both honor the same kill-switch and registry checks as the buffered helpers.

export interface StreamTextWriterOptions {
  topic: string;
  destinationIdentities?: string[];
  attributes?: Record<string, string>;
  /** Optional pre-known total size in characters (informational only). */
  totalSize?: number;
}

export interface StreamBytesWriterOptions {
  topic: string;
  destinationIdentities?: string[];
  mimeType?: string;
  name?: string;
  attributes?: Record<string, string>;
  /** Optional pre-known total size in bytes (informational only). */
  totalSize?: number;
}

/**
 * Open an incremental text stream. Returns a writer with:
 *   - `write(chunk: string)` — push a partial chunk (await for backpressure)
 *   - `close()` — finalize the stream
 *   - `info.id` — stream id (for correlating with receiver)
 *
 * Receivers register with `registerTextStreamHandler` exactly as for
 * `sendText`; the handler is invoked once after the stream closes with the
 * fully-drained text.
 */
export async function streamText(
  scope: StreamScope,
  id: string,
  opts: StreamTextWriterOptions,
) {
  const enabled = await isLiveKitEnabled('streams');
  if (!enabled) throw new Error('streams_disabled');
  const entry = registry.get(key(scope, id));
  if (!entry) throw new Error('room_not_registered');
  const writer = await entry.room.localParticipant.streamText({
    topic: opts.topic,
    destinationIdentities: opts.destinationIdentities,
    attributes: opts.attributes,
    totalSize: opts.totalSize,
  } as any);
  return writer;
}

/**
 * Open an incremental byte stream. Returns a writer with:
 *   - `write(chunk: Uint8Array)` — push a partial chunk (await for backpressure)
 *   - `close()` — finalize the stream
 *
 * Use for chunked uploads with progress, partial binary payloads, or any
 * payload too large to buffer into a single Blob/File.
 */
export async function streamBytes(
  scope: StreamScope,
  id: string,
  opts: StreamBytesWriterOptions,
) {
  const enabled = await isLiveKitEnabled('streams');
  if (!enabled) throw new Error('streams_disabled');
  const entry = registry.get(key(scope, id));
  if (!entry) throw new Error('room_not_registered');
  // streamBytes was added in livekit-client 2.10+. On 2.9.x (matching the
  // self-hosted server) this API is unavailable — callers must fall back to
  // data-channel publish paths. We surface a typed error rather than crash.
  const lp = entry.room.localParticipant as unknown as {
    streamBytes?: (o: unknown) => Promise<unknown>;
  };
  if (typeof lp.streamBytes !== 'function') {
    throw new Error('streamBytes_unsupported_on_server');
  }
  const writer = await lp.streamBytes({
    topic: opts.topic,
    destinationIdentities: opts.destinationIdentities,
    mimeType: opts.mimeType,
    name: opts.name,
    attributes: opts.attributes,
    totalSize: opts.totalSize,
  });
  return writer;
}

// ─── helpers ──────────────────────────────────────────────────────────────


async function drainAsyncIterableText(reader: AsyncIterable<string>): Promise<string> {
  let out = '';
  for await (const chunk of reader) out += chunk;
  return out;
}

/** Test-only registry inspector. */
export function _isStreamRoomRegistered(scope: StreamScope, id: string): boolean {
  return registry.has(key(scope, id));
}
