project_id = "pppcwawjjpwwrmvezcdy"

[functions.webrtc-signaling]
verify_jwt = false

[functions.live-stream]
verify_jwt = false

[functions.party-room]
verify_jwt = false

[functions.presence]
verify_jwt = false

[functions.gift-service]
verify_jwt = false

[functions.agora-token]
verify_jwt = false

[functions.agency-weekly-transfer]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.send-password-otp]
verify_jwt = false

[functions.detect-phone-number]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.admin-phone-alert]
verify_jwt = false

[functions.game-provider]
verify_jwt = false

[functions.r2-proxy]
verify_jwt = false

[functions.support-chat]
verify_jwt = false

[functions.analyze-error]
verify_jwt = false

[functions.distribute-leaderboard-rewards]
verify_jwt = false

[functions.ai-chat-reply]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.validate-admin-token]
verify_jwt = false

[functions.admin-2fa-otp]
verify_jwt = false

[functions.detect-vpn]
verify_jwt = false

[functions.get-admin-tokens]
verify_jwt = false

[functions.force-reset-guest-password]
verify_jwt = false

[functions.scan-image-contact]
verify_jwt = false

[functions.detect-country]
verify_jwt = false

[functions.payroll-helper-bonus]
verify_jwt = false

[functions.push-on-notification]
verify_jwt = false

[functions.face-check]
verify_jwt = false

[functions.auto-face-verify]
verify_jwt = false

[functions.content-moderate]
verify_jwt = false

[functions.r2-upload]
verify_jwt = false

[functions.livekit-token]
verify_jwt = false

[functions.livekit-egress]
verify_jwt = false

[functions.gmail-support]
verify_jwt = false

[functions.send-email-otp]
verify_jwt = false

[functions.verify-email-otp]
verify_jwt = false

[functions.admin-reset-user-password]
verify_jwt = false

[functions.verify-google-purchase]
verify_jwt = false

[functions.admin-verify-purchase]
verify_jwt = false

[functions.admin-sync-auth]
verify_jwt = false

[functions.admin-reset-password-whatsapp]
verify_jwt = false

[functions.admin-lookup-phone]
verify_jwt = false

[functions.send-app-notification]
verify_jwt = false

[functions.tencent-beauty-sign]
verify_jwt = false

[functions.create-stripe-payment]
verify_jwt = false

[functions.verify-stripe-payment]
verify_jwt = false

[functions.create-local-payment]
verify_jwt = false

[functions.local-payment-ipn]
verify_jwt = false

[functions.create-zinipay-payment]
verify_jwt = false

[functions.zinipay-ipn]
verify_jwt = false

[functions.verify-zinipay-payment]
verify_jwt = false

[functions.send-reengagement-push]
verify_jwt = false
