/// Native platform setup notes — MeriLive Flutter app.
///
/// The `android/` and `ios/` folders are not committed here; they are
/// generated by `flutter create .` on the developer machine. When they
/// exist, the following snippets MUST be merged in so the Dart code we
/// already wrote works end-to-end.
///
/// -----------------------------------------------------------------------
/// 1. AndroidManifest.xml
///    File: android/app/src/main/AndroidManifest.xml
///    Location: inside <application><activity android:name=".MainActivity">
/// -----------------------------------------------------------------------
///
/// <!-- Supabase PKCE / password-reset deep link -->
/// <intent-filter android:autoVerify="false">
///     <action android:name="android.intent.action.VIEW" />
///     <category android:name="android.intent.category.DEFAULT" />
///     <category android:name="android.intent.category.BROWSABLE" />
///     <data android:scheme="merilive" android:host="auth-callback" />
///     <data android:scheme="merilive" android:host="reset-password" />
/// </intent-filter>
///
/// <!-- HTTPS fallback for magic-link tap in Gmail / WhatsApp -->
/// <intent-filter android:autoVerify="true">
///     <action android:name="android.intent.action.VIEW" />
///     <category android:name="android.intent.category.DEFAULT" />
///     <category android:name="android.intent.category.BROWSABLE" />
///     <data android:scheme="https"
///           android:host="merilive.top"
///           android:pathPrefix="/auth/callback" />
///     <data android:scheme="https"
///           android:host="merilive.top"
///           android:pathPrefix="/reset-password" />
/// </intent-filter>
///
/// Also add — top-level <manifest> permissions:
///   <uses-permission android:name="android.permission.INTERNET" />
///   <uses-permission android:name="android.permission.CAMERA" />
///   <uses-permission android:name="android.permission.RECORD_AUDIO" />
///   <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
///   <uses-permission android:name="android.permission.WAKE_LOCK" />
///
/// -----------------------------------------------------------------------
/// 2. iOS Info.plist
///    File: ios/Runner/Info.plist
/// -----------------------------------------------------------------------
///
/// <key>CFBundleURLTypes</key>
/// <array>
///     <dict>
///         <key>CFBundleURLName</key>
///         <string>com.merilive.auth</string>
///         <key>CFBundleURLSchemes</key>
///         <array>
///             <string>merilive</string>
///         </array>
///     </dict>
/// </array>
///
/// <key>NSCameraUsageDescription</key>
/// <string>MeriLive needs camera access for live streaming, private calls and party rooms.</string>
/// <key>NSMicrophoneUsageDescription</key>
/// <string>MeriLive needs microphone access for live streaming, calls and party rooms.</string>
/// <key>NSPhotoLibraryUsageDescription</key>
/// <string>MeriLive needs photo access so you can pick your profile picture.</string>
///
/// -----------------------------------------------------------------------
/// 3. Supabase dashboard — Auth → URL Configuration
/// -----------------------------------------------------------------------
///
/// Add to "Additional Redirect URLs":
///   • merilive://auth-callback
///   • merilive://reset-password
///   • https://merilive.top/auth/callback
///   • https://merilive.top/reset-password
///
/// Site URL stays the web app URL so existing web magic-links continue to
/// work.
///
/// -----------------------------------------------------------------------
/// 4. app_links wiring in Dart (already scaffolded in `lib/main.dart`)
/// -----------------------------------------------------------------------
///
/// The `app_links` package listens to inbound `merilive://…` URIs and the
/// router pushes `/auth/callback` or `/reset-password` accordingly. No
/// further code changes are needed once the manifests above are added and
/// the native folders are re-synced with `flutter pub get && flutter clean`.
library merilive_native_setup;
