-- Add missing columns to gift_transactions
ALTER TABLE public.gift_transactions ADD COLUMN IF NOT EXISTS reel_id uuid;
ALTER TABLE public.gift_transactions ADD COLUMN IF NOT EXISTS coin_cost integer DEFAULT 0;
ALTER TABLE public.gift_transactions ADD COLUMN IF NOT EXISTS sender_type text;

-- Now create all 128 triggers
DROP TRIGGER IF EXISTS auto_assign_payroll ON public.payroll_requests;
CREATE TRIGGER auto_assign_payroll BEFORE INSERT ON public.payroll_requests FOR EACH ROW EXECUTE FUNCTION public.distribute_payroll_requests();
DROP TRIGGER IF EXISTS on_call_ended_earnings ON public.private_calls;
CREATE TRIGGER on_call_ended_earnings AFTER UPDATE ON public.private_calls FOR EACH ROW EXECUTE FUNCTION public.update_host_call_earnings();
DROP TRIGGER IF EXISTS on_gift_transaction_earnings ON public.gift_transactions;
CREATE TRIGGER on_gift_transaction_earnings AFTER INSERT ON public.gift_transactions FOR EACH ROW EXECUTE FUNCTION public.update_host_earnings_on_gift();
DROP TRIGGER IF EXISTS on_helper_reply_added ON public.helper_message_replies;
CREATE TRIGGER on_helper_reply_added AFTER INSERT ON public.helper_message_replies FOR EACH ROW EXECUTE FUNCTION public.update_message_has_replies();
DROP TRIGGER IF EXISTS on_profile_created_assign_uid ON public.profiles;
CREATE TRIGGER on_profile_created_assign_uid BEFORE INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.assign_app_uid();
DROP TRIGGER IF EXISTS on_reel_gift_trigger ON public.gift_transactions;
CREATE TRIGGER on_reel_gift_trigger AFTER INSERT ON public.gift_transactions FOR EACH ROW WHEN ((new.reel_id IS NOT NULL)) EXECUTE FUNCTION public.handle_reel_gift();
DROP TRIGGER IF EXISTS on_room_participant_change ON public.party_room_participants;
CREATE TRIGGER on_room_participant_change AFTER INSERT OR UPDATE ON public.party_room_participants FOR EACH ROW EXECUTE FUNCTION public.update_room_participant_count();
DROP TRIGGER IF EXISTS on_stream_end ON public.live_streams;
CREATE TRIGGER on_stream_end AFTER UPDATE ON public.live_streams FOR EACH ROW EXECUTE FUNCTION public.update_host_hours_on_stream_end();
DROP TRIGGER IF EXISTS on_stream_viewer_change ON public.stream_viewers;
CREATE TRIGGER on_stream_viewer_change AFTER INSERT OR UPDATE ON public.stream_viewers FOR EACH ROW EXECUTE FUNCTION public.update_stream_stats();
DROP TRIGGER IF EXISTS protect_sensitive_columns_trigger ON public.profiles;
CREATE TRIGGER protect_sensitive_columns_trigger BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.protect_sensitive_profile_columns();
DROP TRIGGER IF EXISTS protect_task_progress_trigger ON public.user_task_progress;
CREATE TRIGGER protect_task_progress_trigger BEFORE INSERT OR UPDATE ON public.user_task_progress FOR EACH ROW EXECUTE FUNCTION public.protect_task_progress_writes();
DROP TRIGGER IF EXISTS set_app_uid_trigger ON public.profiles;
CREATE TRIGGER set_app_uid_trigger BEFORE INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.set_app_uid_on_insert();
DROP TRIGGER IF EXISTS trg_admin_notify_face_verification ON public.face_verification_submissions;
CREATE TRIGGER trg_admin_notify_face_verification AFTER INSERT ON public.face_verification_submissions FOR EACH ROW EXECUTE FUNCTION public.trigger_admin_notify_face_verification();
DROP TRIGGER IF EXISTS trg_admin_notify_helper_application ON public.helper_applications;
CREATE TRIGGER trg_admin_notify_helper_application AFTER INSERT ON public.helper_applications FOR EACH ROW EXECUTE FUNCTION public.trigger_admin_notify_helper_application();
DROP TRIGGER IF EXISTS trg_admin_notify_helper_topup ON public.helper_topup_requests;
CREATE TRIGGER trg_admin_notify_helper_topup AFTER INSERT ON public.helper_topup_requests FOR EACH ROW EXECUTE FUNCTION public.trigger_admin_notify_helper_topup();
DROP TRIGGER IF EXISTS trg_admin_notify_helper_upgrade ON public.helper_upgrade_requests;
CREATE TRIGGER trg_admin_notify_helper_upgrade AFTER INSERT ON public.helper_upgrade_requests FOR EACH ROW EXECUTE FUNCTION public.trigger_admin_notify_helper_upgrade();
DROP TRIGGER IF EXISTS trg_admin_notify_new_agency ON public.agencies;
CREATE TRIGGER trg_admin_notify_new_agency AFTER INSERT ON public.agencies FOR EACH ROW EXECUTE FUNCTION public.trigger_admin_notify_new_agency();
DROP TRIGGER IF EXISTS trg_admin_notify_support_ticket ON public.support_tickets;
CREATE TRIGGER trg_admin_notify_support_ticket AFTER INSERT ON public.support_tickets FOR EACH ROW EXECUTE FUNCTION public.trigger_admin_notify_support_ticket();
DROP TRIGGER IF EXISTS trg_admin_notify_withdrawal ON public.agency_withdrawals;
CREATE TRIGGER trg_admin_notify_withdrawal AFTER INSERT ON public.agency_withdrawals FOR EACH ROW EXECUTE FUNCTION public.trigger_admin_notify_withdrawal();
DROP TRIGGER IF EXISTS trg_auto_recalc_host_level ON public.profiles;
CREATE TRIGGER trg_auto_recalc_host_level BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.auto_recalc_host_level();
DROP TRIGGER IF EXISTS trg_auto_update_helper_level ON public.topup_helpers;
CREATE TRIGGER trg_auto_update_helper_level BEFORE UPDATE OF total_level_upgrade_cost ON public.topup_helpers FOR EACH ROW EXECUTE FUNCTION public.recalculate_helper_trader_level();
DROP TRIGGER IF EXISTS trg_auto_update_helper_level_insert ON public.topup_helpers;
CREATE TRIGGER trg_auto_update_helper_level_insert BEFORE INSERT ON public.topup_helpers FOR EACH ROW EXECUTE FUNCTION public.recalculate_helper_trader_level();
DROP TRIGGER IF EXISTS trg_notify_helper_on_admin_message ON public.helper_admin_messages;
CREATE TRIGGER trg_notify_helper_on_admin_message AFTER INSERT ON public.helper_admin_messages FOR EACH ROW EXECUTE FUNCTION public.notify_helper_on_admin_message();
DROP TRIGGER IF EXISTS trg_notify_reporter_on_resolution ON public.user_reports;
CREATE TRIGGER trg_notify_reporter_on_resolution AFTER UPDATE ON public.user_reports FOR EACH ROW EXECUTE FUNCTION public.notify_reporter_on_resolution();
DROP TRIGGER IF EXISTS trg_notify_user_on_admin_reply ON public.support_messages;
CREATE TRIGGER trg_notify_user_on_admin_reply AFTER INSERT ON public.support_messages FOR EACH ROW EXECUTE FUNCTION public.notify_user_on_admin_reply();
DROP TRIGGER IF EXISTS trg_sync_agency_commission_rate ON public.agencies;
CREATE TRIGGER trg_sync_agency_commission_rate BEFORE INSERT OR UPDATE OF level ON public.agencies FOR EACH ROW EXECUTE FUNCTION public.sync_agency_commission_rate();
DROP TRIGGER IF EXISTS trg_sync_message_read_status ON public.messages;
CREATE TRIGGER trg_sync_message_read_status BEFORE UPDATE ON public.messages FOR EACH ROW EXECUTE FUNCTION public.sync_message_read_status();
DROP TRIGGER IF EXISTS trg_sync_payroll_helper_agency ON public.topup_helpers;
CREATE TRIGGER trg_sync_payroll_helper_agency AFTER INSERT OR UPDATE OF trader_level, payroll_enabled, is_verified ON public.topup_helpers FOR EACH ROW EXECUTE FUNCTION public.sync_payroll_helper_agency_level();
DROP TRIGGER IF EXISTS trg_update_agency_level ON public.profiles;
CREATE TRIGGER trg_update_agency_level AFTER UPDATE OF total_earnings ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.update_agency_level_on_earnings();
DROP TRIGGER IF EXISTS trg_validate_task_claim_state ON public.user_task_progress;
CREATE TRIGGER trg_validate_task_claim_state BEFORE INSERT OR UPDATE ON public.user_task_progress FOR EACH ROW EXECUTE FUNCTION public.validate_user_task_progress_claim();
DROP TRIGGER IF EXISTS trigger_add_weekly_earnings ON public.gift_transactions;
CREATE TRIGGER trigger_add_weekly_earnings AFTER INSERT ON public.gift_transactions FOR EACH ROW EXECUTE FUNCTION public.add_to_weekly_earnings();
DROP TRIGGER IF EXISTS trigger_agency_ranking_update ON public.agency_performance;
CREATE TRIGGER trigger_agency_ranking_update AFTER INSERT OR DELETE OR UPDATE ON public.agency_performance FOR EACH ROW EXECUTE FUNCTION public.update_agency_ranking_metrics();
DROP TRIGGER IF EXISTS trigger_agency_withdrawal_notification ON public.agency_withdrawals;
CREATE TRIGGER trigger_agency_withdrawal_notification AFTER UPDATE ON public.agency_withdrawals FOR EACH ROW EXECUTE FUNCTION public.notify_agency_withdrawal_status();
DROP TRIGGER IF EXISTS trigger_auto_agency_commission ON public.gift_transactions;
CREATE TRIGGER trigger_auto_agency_commission AFTER INSERT ON public.gift_transactions FOR EACH ROW EXECUTE FUNCTION public.auto_credit_agency_commission();
DROP TRIGGER IF EXISTS trigger_auto_agency_commission_call ON public.private_calls;
CREATE TRIGGER trigger_auto_agency_commission_call AFTER UPDATE ON public.private_calls FOR EACH ROW EXECUTE FUNCTION public.auto_credit_agency_commission_from_call();
DROP TRIGGER IF EXISTS trigger_auto_assign_admin_frame ON public.user_roles;
CREATE TRIGGER trigger_auto_assign_admin_frame AFTER INSERT ON public.user_roles FOR EACH ROW EXECUTE FUNCTION public.auto_assign_role_frame();
DROP TRIGGER IF EXISTS trigger_auto_assign_agency_frame ON public.agencies;
CREATE TRIGGER trigger_auto_assign_agency_frame AFTER INSERT ON public.agencies FOR EACH ROW EXECUTE FUNCTION public.auto_assign_role_frame();
DROP TRIGGER IF EXISTS trigger_auto_assign_helper_frame ON public.topup_helpers;
CREATE TRIGGER trigger_auto_assign_helper_frame AFTER INSERT ON public.topup_helpers FOR EACH ROW EXECUTE FUNCTION public.auto_assign_role_frame();
DROP TRIGGER IF EXISTS trigger_auto_assign_level_frame ON public.profiles;
CREATE TRIGGER trigger_auto_assign_level_frame BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.auto_assign_level_frame();
DROP TRIGGER IF EXISTS trigger_auto_convert_account_by_gender ON public.profiles;
CREATE TRIGGER trigger_auto_convert_account_by_gender BEFORE INSERT OR UPDATE OF gender ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.auto_convert_account_by_gender();
DROP TRIGGER IF EXISTS trigger_auto_update_level_coins ON public.coin_transfers;
CREATE TRIGGER trigger_auto_update_level_coins AFTER INSERT ON public.coin_transfers FOR EACH ROW EXECUTE FUNCTION public.auto_update_level();
DROP TRIGGER IF EXISTS trigger_auto_update_level_gift ON public.gift_transactions;
CREATE TRIGGER trigger_auto_update_level_gift AFTER INSERT ON public.gift_transactions FOR EACH ROW EXECUTE FUNCTION public.auto_update_level();
DROP TRIGGER IF EXISTS trigger_auto_update_level_profiles ON public.profiles;
CREATE TRIGGER trigger_auto_update_level_profiles AFTER UPDATE OF total_recharged, total_consumption ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.update_user_level_comprehensive();
DROP TRIGGER IF EXISTS trigger_broadcast_notice ON public.admin_notices;
CREATE TRIGGER trigger_broadcast_notice AFTER INSERT ON public.admin_notices FOR EACH ROW EXECUTE FUNCTION public.broadcast_notice_to_users();
DROP TRIGGER IF EXISTS trigger_check_auto_ban ON public.chat_moderation_logs;
CREATE TRIGGER trigger_check_auto_ban AFTER INSERT ON public.chat_moderation_logs FOR EACH ROW EXECUTE FUNCTION public.check_auto_ban_threshold();
DROP TRIGGER IF EXISTS trigger_check_room_active ON public.party_room_participants;
CREATE TRIGGER trigger_check_room_active AFTER UPDATE ON public.party_room_participants FOR EACH ROW EXECUTE FUNCTION public.check_room_active_on_participant_leave();
DROP TRIGGER IF EXISTS trigger_cleanup_admin_otps ON public.admin_login_otps;
CREATE TRIGGER trigger_cleanup_admin_otps AFTER INSERT ON public.admin_login_otps FOR EACH ROW EXECUTE FUNCTION public.cleanup_expired_admin_otps();
DROP TRIGGER IF EXISTS trigger_coin_transfer_notification ON public.coin_transfers;
CREATE TRIGGER trigger_coin_transfer_notification AFTER INSERT ON public.coin_transfers FOR EACH ROW EXECUTE FUNCTION public.notify_coin_transfer();
DROP TRIGGER IF EXISTS trigger_diamond_exchange_notification ON public.agency_diamond_transactions;
CREATE TRIGGER trigger_diamond_exchange_notification AFTER INSERT ON public.agency_diamond_transactions FOR EACH ROW EXECUTE FUNCTION public.notify_diamond_exchange();
DROP TRIGGER IF EXISTS trigger_enforce_permanent_ban ON public.profiles;
CREATE TRIGGER trigger_enforce_permanent_ban BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.enforce_permanent_ban();
DROP TRIGGER IF EXISTS trigger_enforce_permanent_live_ban ON public.live_bans;
CREATE TRIGGER trigger_enforce_permanent_live_ban BEFORE UPDATE ON public.live_bans FOR EACH ROW EXECUTE FUNCTION public.enforce_permanent_live_ban();
DROP TRIGGER IF EXISTS trigger_handle_user_ban ON public.profiles;
CREATE TRIGGER trigger_handle_user_ban AFTER UPDATE OF is_blocked ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.handle_user_ban();
DROP TRIGGER IF EXISTS trigger_helper_level_notification ON public.helper_applications;
CREATE TRIGGER trigger_helper_level_notification AFTER UPDATE ON public.helper_applications FOR EACH ROW EXECUTE FUNCTION public.notify_helper_level_change();
DROP TRIGGER IF EXISTS trigger_notify_gift_received ON public.gift_transactions;
CREATE TRIGGER trigger_notify_gift_received AFTER INSERT ON public.gift_transactions FOR EACH ROW EXECUTE FUNCTION public.notify_on_gift_received();
DROP TRIGGER IF EXISTS trigger_notify_helper_on_new_order ON public.helper_orders;
CREATE TRIGGER trigger_notify_helper_on_new_order AFTER INSERT ON public.helper_orders FOR EACH ROW EXECUTE FUNCTION public.notify_helper_on_new_order();
DROP TRIGGER IF EXISTS trigger_notify_host_application ON public.host_applications;
CREATE TRIGGER trigger_notify_host_application AFTER UPDATE ON public.host_applications FOR EACH ROW EXECUTE FUNCTION public.notify_on_host_application_status();
DROP TRIGGER IF EXISTS trigger_notify_live_started ON public.live_streams;
CREATE TRIGGER trigger_notify_live_started AFTER INSERT ON public.live_streams FOR EACH ROW EXECUTE FUNCTION public.notify_on_live_stream_started();
DROP TRIGGER IF EXISTS trigger_notify_new_follower ON public.followers;
CREATE TRIGGER trigger_notify_new_follower AFTER INSERT ON public.followers FOR EACH ROW EXECUTE FUNCTION public.notify_on_new_follower();
DROP TRIGGER IF EXISTS trigger_notify_recharge_completed ON public.recharge_transactions;
CREATE TRIGGER trigger_notify_recharge_completed AFTER UPDATE ON public.recharge_transactions FOR EACH ROW EXECUTE FUNCTION public.notify_on_recharge_completed();
DROP TRIGGER IF EXISTS trigger_notify_withdrawal_status ON public.agency_withdrawals;
CREATE TRIGGER trigger_notify_withdrawal_status AFTER UPDATE ON public.agency_withdrawals FOR EACH ROW EXECUTE FUNCTION public.notify_on_withdrawal_status();
DROP TRIGGER IF EXISTS trigger_prevent_agency_balance_manipulation ON public.agencies;
CREATE TRIGGER trigger_prevent_agency_balance_manipulation BEFORE UPDATE ON public.agencies FOR EACH ROW EXECUTE FUNCTION public.prevent_agency_balance_manipulation();
DROP TRIGGER IF EXISTS trigger_prevent_balance_manipulation ON public.profiles;
CREATE TRIGGER trigger_prevent_balance_manipulation BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.prevent_balance_manipulation();
DROP TRIGGER IF EXISTS trigger_prevent_helper_wallet_manipulation ON public.topup_helpers;
CREATE TRIGGER trigger_prevent_helper_wallet_manipulation BEFORE UPDATE ON public.topup_helpers FOR EACH ROW EXECUTE FUNCTION public.prevent_helper_wallet_manipulation();
DROP TRIGGER IF EXISTS trigger_prevent_negative_agency_balance ON public.agencies;
CREATE TRIGGER trigger_prevent_negative_agency_balance BEFORE UPDATE ON public.agencies FOR EACH ROW EXECUTE FUNCTION public.prevent_negative_agency_balance();
DROP TRIGGER IF EXISTS trigger_push_notification_on_insert ON public.notifications;
CREATE TRIGGER trigger_push_notification_on_insert AFTER INSERT ON public.notifications FOR EACH ROW EXECUTE FUNCTION public.trigger_push_on_notification();
DROP TRIGGER IF EXISTS trigger_set_ticket_sender_sector ON public.support_tickets;
CREATE TRIGGER trigger_set_ticket_sender_sector BEFORE INSERT ON public.support_tickets FOR EACH ROW EXECUTE FUNCTION public.set_ticket_sender_sector();
DROP TRIGGER IF EXISTS trigger_sync_commission_rates ON public.agency_level_tiers;
CREATE TRIGGER trigger_sync_commission_rates AFTER UPDATE ON public.agency_level_tiers FOR EACH ROW EXECUTE FUNCTION public.sync_commission_rates();
DROP TRIGGER IF EXISTS trigger_sync_country_fields ON public.profiles;
CREATE TRIGGER trigger_sync_country_fields BEFORE INSERT OR UPDATE OF country_code ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.sync_country_fields();
DROP TRIGGER IF EXISTS trigger_topup_status_notification ON public.helper_topup_requests;
CREATE TRIGGER trigger_topup_status_notification AFTER UPDATE ON public.helper_topup_requests FOR EACH ROW EXECUTE FUNCTION public.notify_topup_status_change();
DROP TRIGGER IF EXISTS trigger_update_agency_level ON public.agencies;
CREATE TRIGGER trigger_update_agency_level BEFORE UPDATE ON public.agencies FOR EACH ROW EXECUTE FUNCTION public.update_agency_level();
DROP TRIGGER IF EXISTS trigger_update_consumption_on_recharge ON public.recharge_transactions;
CREATE TRIGGER trigger_update_consumption_on_recharge AFTER UPDATE ON public.recharge_transactions FOR EACH ROW EXECUTE FUNCTION public.update_consumption_on_recharge();
DROP TRIGGER IF EXISTS trigger_update_game_stats ON public.game_transactions;
CREATE TRIGGER trigger_update_game_stats AFTER INSERT ON public.game_transactions FOR EACH ROW EXECUTE FUNCTION public.update_game_stats();
DROP TRIGGER IF EXISTS trigger_update_level_on_gift_log ON public.gift_transaction_logs;
CREATE TRIGGER trigger_update_level_on_gift_log AFTER INSERT ON public.gift_transaction_logs FOR EACH ROW EXECUTE FUNCTION public.auto_update_level();
DROP TRIGGER IF EXISTS trigger_update_level_on_transfer ON public.coin_transfers;
CREATE TRIGGER trigger_update_level_on_transfer AFTER INSERT ON public.coin_transfers FOR EACH ROW EXECUTE FUNCTION public.auto_update_level();
DROP TRIGGER IF EXISTS trigger_update_total_recharged ON public.recharge_transactions;
CREATE TRIGGER trigger_update_total_recharged AFTER UPDATE ON public.recharge_transactions FOR EACH ROW EXECUTE FUNCTION public.update_total_recharged();
DROP TRIGGER IF EXISTS trigger_welcome_bonus ON public.profiles;
CREATE TRIGGER trigger_welcome_bonus AFTER INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.grant_welcome_bonus();
DROP TRIGGER IF EXISTS update_admin_stats_updated_at ON public.admin_stats;
CREATE TRIGGER update_admin_stats_updated_at BEFORE UPDATE ON public.admin_stats FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_admin_users_updated_at ON public.admin_users;
CREATE TRIGGER update_admin_users_updated_at BEFORE UPDATE ON public.admin_users FOR EACH ROW EXECUTE FUNCTION public.update_admin_users_timestamp();
DROP TRIGGER IF EXISTS update_agencies_updated_at ON public.agencies;
CREATE TRIGGER update_agencies_updated_at BEFORE UPDATE ON public.agencies FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_agency_level_on_performance ON public.agency_performance;
CREATE TRIGGER update_agency_level_on_performance AFTER INSERT OR UPDATE ON public.agency_performance FOR EACH ROW EXECUTE FUNCTION public.update_agency_level_from_performance();
DROP TRIGGER IF EXISTS update_agency_performance_updated_at ON public.agency_performance;
CREATE TRIGGER update_agency_performance_updated_at BEFORE UPDATE ON public.agency_performance FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_agency_policy_settings_updated_at ON public.agency_policy_settings;
CREATE TRIGGER update_agency_policy_settings_updated_at BEFORE UPDATE ON public.agency_policy_settings FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_agency_rankings_updated_at ON public.agency_rankings;
CREATE TRIGGER update_agency_rankings_updated_at BEFORE UPDATE ON public.agency_rankings FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_allowed_external_links_updated_at ON public.allowed_external_links;
CREATE TRIGGER update_allowed_external_links_updated_at BEFORE UPDATE ON public.allowed_external_links FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_app_content_updated_at ON public.app_content;
CREATE TRIGGER update_app_content_updated_at BEFORE UPDATE ON public.app_content FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_app_settings_updated_at ON public.app_settings;
CREATE TRIGGER update_app_settings_updated_at BEFORE UPDATE ON public.app_settings FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_banners_updated_at ON public.banners;
CREATE TRIGGER update_banners_updated_at BEFORE UPDATE ON public.banners FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_channels_updated_at ON public.channels;
CREATE TRIGGER update_channels_updated_at BEFORE UPDATE ON public.channels FOR EACH ROW EXECUTE FUNCTION public.update_channels_updated_at();
DROP TRIGGER IF EXISTS update_coin_packages_timestamp ON public.coin_packages;
CREATE TRIGGER update_coin_packages_timestamp BEFORE UPDATE ON public.coin_packages FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_conversation_on_message ON public.messages;
CREATE TRIGGER update_conversation_on_message AFTER INSERT ON public.messages FOR EACH ROW EXECUTE FUNCTION public.update_conversation_timestamp();
DROP TRIGGER IF EXISTS update_currency_rates_timestamp ON public.currency_rates;
CREATE TRIGGER update_currency_rates_timestamp BEFORE UPDATE ON public.currency_rates FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_device_tokens_updated_at ON public.device_tokens;
CREATE TRIGGER update_device_tokens_updated_at BEFORE UPDATE ON public.device_tokens FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_entry_banners_updated_at ON public.entry_banners;
CREATE TRIGGER update_entry_banners_updated_at BEFORE UPDATE ON public.entry_banners FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_entry_name_bars_updated_at ON public.entry_name_bars;
CREATE TRIGGER update_entry_name_bars_updated_at BEFORE UPDATE ON public.entry_name_bars FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_face_verification_submissions_updated_at ON public.face_verification_submissions;
CREATE TRIGGER update_face_verification_submissions_updated_at BEFORE UPDATE ON public.face_verification_submissions FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_feature_level_requirements_updated_at ON public.feature_level_requirements;
CREATE TRIGGER update_feature_level_requirements_updated_at BEFORE UPDATE ON public.feature_level_requirements FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_game_providers_updated_at ON public.game_providers;
CREATE TRIGGER update_game_providers_updated_at BEFORE UPDATE ON public.game_providers FOR EACH ROW EXECUTE FUNCTION public.update_game_provider_timestamp();
DROP TRIGGER IF EXISTS update_group_member_count_trigger ON public.group_members;
CREATE TRIGGER update_group_member_count_trigger AFTER INSERT OR DELETE ON public.group_members FOR EACH ROW EXECUTE FUNCTION public.update_group_member_count();
DROP TRIGGER IF EXISTS update_helper_country_payment_methods_updated_at ON public.helper_country_payment_methods;
CREATE TRIGGER update_helper_country_payment_methods_updated_at BEFORE UPDATE ON public.helper_country_payment_methods FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_helper_topup_requests_updated_at ON public.helper_topup_requests;
CREATE TRIGGER update_helper_topup_requests_updated_at BEFORE UPDATE ON public.helper_topup_requests FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_helper_upgrade_requests_updated_at ON public.helper_upgrade_requests;
CREATE TRIGGER update_helper_upgrade_requests_updated_at BEFORE UPDATE ON public.helper_upgrade_requests FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_host_applications_updated_at ON public.host_applications;
CREATE TRIGGER update_host_applications_updated_at BEFORE UPDATE ON public.host_applications FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_host_level_on_gift ON public.gift_transactions;
CREATE TRIGGER update_host_level_on_gift AFTER INSERT ON public.gift_transactions FOR EACH ROW EXECUTE FUNCTION public.update_host_level_on_earnings();
DROP TRIGGER IF EXISTS update_landing_page_sections_updated_at ON public.landing_page_sections;
CREATE TRIGGER update_landing_page_sections_updated_at BEFORE UPDATE ON public.landing_page_sections FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_leaderboard_reward_config_updated_at ON public.leaderboard_reward_config;
CREATE TRIGGER update_leaderboard_reward_config_updated_at BEFORE UPDATE ON public.leaderboard_reward_config FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_new_host_live_bonus_progress_updated_at ON public.new_host_live_bonus_progress;
CREATE TRIGGER update_new_host_live_bonus_progress_updated_at BEFORE UPDATE ON public.new_host_live_bonus_progress FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_new_host_live_bonus_settings_updated_at ON public.new_host_live_bonus_settings;
CREATE TRIGGER update_new_host_live_bonus_settings_updated_at BEFORE UPDATE ON public.new_host_live_bonus_settings FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_news_sources_updated_at ON public.news_sources;
CREATE TRIGGER update_news_sources_updated_at BEFORE UPDATE ON public.news_sources FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_party_room_banners_updated_at ON public.party_room_banners;
CREATE TRIGGER update_party_room_banners_updated_at BEFORE UPDATE ON public.party_room_banners FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_payment_gateways_updated_at ON public.payment_gateways;
CREATE TRIGGER update_payment_gateways_updated_at BEFORE UPDATE ON public.payment_gateways FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_payment_methods_updated_at ON public.payment_methods;
CREATE TRIGGER update_payment_methods_updated_at BEFORE UPDATE ON public.payment_methods FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_payment_transactions_updated_at ON public.payment_transactions;
CREATE TRIGGER update_payment_transactions_updated_at BEFORE UPDATE ON public.payment_transactions FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_pk_battles_updated_at ON public.pk_battles;
CREATE TRIGGER update_pk_battles_updated_at BEFORE UPDATE ON public.pk_battles FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_pk_competitions_updated_at ON public.pk_competitions;
CREATE TRIGGER update_pk_competitions_updated_at BEFORE UPDATE ON public.pk_competitions FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_pk_participants_updated_at ON public.pk_participants;
CREATE TRIGGER update_pk_participants_updated_at BEFORE UPDATE ON public.pk_participants FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_pk_reward_banners_updated_at ON public.pk_reward_banners;
CREATE TRIGGER update_pk_reward_banners_updated_at BEFORE UPDATE ON public.pk_reward_banners FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_popup_event_banners_updated_at ON public.popup_event_banners;
CREATE TRIGGER update_popup_event_banners_updated_at BEFORE UPDATE ON public.popup_event_banners FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_provider_games_updated_at ON public.provider_games;
CREATE TRIGGER update_provider_games_updated_at BEFORE UPDATE ON public.provider_games FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_role_frames_updated_at ON public.role_frames;
CREATE TRIGGER update_role_frames_updated_at BEFORE UPDATE ON public.role_frames FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_room_welcome_messages_updated_at ON public.room_welcome_messages;
CREATE TRIGGER update_room_welcome_messages_updated_at BEFORE UPDATE ON public.room_welcome_messages FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_stream_recordings_updated_at ON public.stream_recordings;
CREATE TRIGGER update_stream_recordings_updated_at BEFORE UPDATE ON public.stream_recordings FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_subscription_orders_updated_at ON public.subscription_orders;
CREATE TRIGGER update_subscription_orders_updated_at BEFORE UPDATE ON public.subscription_orders FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_support_tickets_updated_at ON public.support_tickets;
CREATE TRIGGER update_support_tickets_updated_at BEFORE UPDATE ON public.support_tickets FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_topup_payment_methods_updated_at ON public.topup_payment_methods;
CREATE TRIGGER update_topup_payment_methods_updated_at BEFORE UPDATE ON public.topup_payment_methods FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_user_reports_updated_at ON public.user_reports;
CREATE TRIGGER update_user_reports_updated_at BEFORE UPDATE ON public.user_reports FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_user_roles_updated_at ON public.user_roles;
CREATE TRIGGER update_user_roles_updated_at BEFORE UPDATE ON public.user_roles FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS update_youtube_sources_updated_at ON public.youtube_sources;
CREATE TRIGGER update_youtube_sources_updated_at BEFORE UPDATE ON public.youtube_sources FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();