-- Pkg352 retry: make frontend admin sidebar sections match DB permission catalog.
CREATE TEMP TABLE tmp_pkg352_frontend_sections (
  section_key text PRIMARY KEY,
  section_name text NOT NULL,
  hub_key text NOT NULL
) ON COMMIT DROP;

INSERT INTO tmp_pkg352_frontend_sections (section_key, section_name, hub_key)
VALUES
  ('agencies', 'All Agencies', 'agency-hub'),
  ('agency-hub', 'Agency Hub', 'agency-hub'),
  ('agency-policy', 'Agency Policy', 'agency-hub'),
  ('ai-image-studio', 'AI Photo Generator', 'settings-hub'),
  ('allowed-links', 'Allowed Links', 'settings-hub'),
  ('animation-store', 'Animation Store', 'visual-hub'),
  ('app-settings-hub', 'App Settings Hub', 'settings-hub'),
  ('app-version', 'App Version', 'settings-hub'),
  ('auto-actions', 'Auto Actions Log', 'moderation-hub'),
  ('balance-deduction', 'Balance Deduction', 'finance-hub'),
  ('banners', 'Banners', 'content-hub'),
  ('beauty-filters', 'Beauty Filters', 'visual-hub'),
  ('blocked', 'Blocked Users', 'user-hub'),
  ('blueprint', 'App Blueprint', 'settings-hub'),
  ('branding', 'Branding', 'settings-hub'),
  ('campaign-banner-hub', '🎯 Campaign Banner Hub', 'content-hub'),
  ('chat-bubbles', 'Chat Bubbles', 'visual-hub'),
  ('chat-inspector', 'Chat Inspector', 'moderation-hub'),
  ('coin-trader-hub', 'Diamond Trader Hub', 'trader-hub'),
  ('coin-traders', 'Diamond Traders', 'trader-hub'),
  ('coins', 'Diamonds Management', 'finance-hub'),
  ('contact-violations', 'Contact Violations', 'moderation-hub'),
  ('content', 'Content Pages', 'content-hub'),
  ('content-management', 'Content Management', 'content-hub'),
  ('cost-monitor', 'Cost Monitor', 'moderation-hub'),
  ('country-distribution', 'Country Distribution', 'user-hub'),
  ('device-approvals', '🔐 Device Approvals', 'settings-hub'),
  ('device-management', 'Device Management', 'settings-hub'),
  ('email-broadcast', 'Email Broadcast', 'settings-hub'),
  ('entry-banners', 'Entry Banners', 'visual-hub'),
  ('entry-bars', 'Entry Bars', 'visual-hub'),
  ('entry-effects', 'Entry Effects', 'visual-hub'),
  ('entry-name-bars', 'Entry Name Bars', 'visual-hub'),
  ('face-verification', 'Face Verification', 'user-hub'),
  ('face-violations', 'Face Violations', 'user-hub'),
  ('feature-levels', 'Feature Levels', 'level-hub'),
  ('finance', 'Finance Management', 'finance-hub'),
  ('frames', 'Avatar Frames', 'visual-hub'),
  ('game-leaderboard', 'Game Leaderboard', 'game-hub'),
  ('game-management', 'Game Management', 'game-hub'),
  ('game-providers', 'Game Providers', 'game-hub'),
  ('game-server', 'Game Server', 'game-hub'),
  ('game-settings', 'Game Settings', 'game-hub'),
  ('gift-transactions', 'Gift Transactions', 'finance-hub'),
  ('gifts', 'Gifts', 'finance-hub'),
  ('gmail-support', 'Gmail Support', 'moderation-hub'),
  ('helper-applications', 'Helper Applications', 'trader-hub'),
  ('helper-management', 'Helper Management', 'trader-hub'),
  ('helper-orders', 'Helper Orders', 'trader-hub'),
  ('helper-requests', 'Helper Requests', 'trader-hub'),
  ('host-applications', 'Host Applications', 'user-hub'),
  ('host-feed-ranking', '🏠 Host Feed Ranking', 'settings-hub'),
  ('host-search', 'Host Search', 'user-hub'),
  ('hosts', 'All Hosts', 'user-hub'),
  ('icon-registry', 'Icon Registry', 'visual-hub'),
  ('invitation-settings', 'Invitation Settings', 'settings-hub'),
  ('landing-page', 'Landing Page', 'settings-hub'),
  ('leaderboard-management', 'Leaderboard', 'content-hub'),
  ('level-management', 'Level Management', 'level-hub'),
  ('level-privileges', 'Level Privileges', 'level-hub'),
  ('level-tiers', 'Level Tiers', 'level-hub'),
  ('level5-helpers', 'Level 5 Helpers', 'trader-hub'),
  ('live-bans', 'Live Bans', 'user-hub'),
  ('livekit-egress', 'LiveKit Egress', 'content-hub'),
  ('livekit-ingress', 'LiveKit Ingress', 'content-hub'),
  ('livekit-rooms', 'LiveKit Rooms', 'content-hub'),
  ('livekit-sip', 'LiveKit SIP', 'content-hub'),
  ('livekit-webhook', 'LiveKit Webhooks', 'content-hub'),
  ('manual-topup', 'Manual Topup', 'finance-hub'),
  ('moderation', 'Moderation', 'user-hub'),
  ('moderation-audit', 'Moderation Audit', 'moderation-hub'),
  ('noble-cards', 'Noble Cards', 'vip-hub'),
  ('noble-subscriptions', 'Noble Subscriptions', 'vip-hub'),
  ('notice-broadcast', 'Notice Broadcast', 'settings-hub'),
  ('notification-templates', 'Notification Templates', 'settings-hub'),
  ('number-sharing', 'Number Sharing', 'moderation-hub'),
  ('onboarding-slides', 'Onboarding Slides', 'settings-hub'),
  ('online-users', 'Online Users', 'user-hub'),
  ('parcel-management', 'Parcel Management', 'settings-hub'),
  ('party-backgrounds', 'Party Backgrounds', 'party-hub'),
  ('party-banners', 'Party Banners', 'party-hub'),
  ('party-discovery-ranking', '🎉 Party Discovery Ranking', 'settings-hub'),
  ('party-management', 'Party Management', 'party-hub'),
  ('party-rooms', 'Party Rooms', 'party-hub'),
  ('payment-gateways', 'Payment Gateways', 'finance-hub'),
  ('payroll-orders', 'Payroll Orders', 'finance-hub'),
  ('pending-approvals', 'Pending Approvals', 'moderation-hub'),
  ('permanent-ban', 'Permanent Ban (3-Step)', 'user-hub'),
  ('popup-banners', 'Popup Event Banners', 'settings-hub'),
  ('pricing-hub', 'Pricing & Commission Hub', 'agency-hub'),
  ('push-broadcast', 'Push Broadcast', 'settings-hub'),
  ('ranking-automation', '🤖 Ranking Automation (AI)', 'settings-hub'),
  ('ranking-rewards', 'Ranking Rewards', 'vip-hub'),
  ('rating-banners', 'Rating Reward Banners', 'settings-hub'),
  ('rating-rewards', 'Rating Rewards', 'content-hub'),
  ('recharge-campaigns', '💎 Recharge Campaigns', 'finance-hub'),
  ('recharge-history', 'Recharge History', 'finance-hub'),
  ('recordings', 'Recordings', 'content-hub'),
  ('reels', 'Reels', 'content-hub'),
  ('reward-claims-history', 'Reward Claims History', 'content-hub'),
  ('rewards-management', 'Rewards Management', 'content-hub'),
  ('role-frames', 'Role Frames', 'visual-hub'),
  ('room-welcome-messages', 'Room Welcome Messages', 'party-hub'),
  ('settings', 'General Settings', 'settings-hub'),
  ('shop', 'Shop', 'finance-hub'),
  ('sip-inbound', 'SIP Inbound', 'content-hub'),
  ('streams', 'Streams', 'content-hub'),
  ('sub-admins', 'Sub-Admin Management', 'settings-hub'),
  ('support-reports', 'Support Reports', 'moderation-hub'),
  ('support-tickets', 'Support Tickets', 'moderation-hub'),
  ('tasks-settings', 'Task Center', 'content-hub'),
  ('theme-manager', '🎨 Event Themes', 'settings-hub'),
  ('today-calls', 'Today''s Calls', 'settings-hub'),
  ('topup-payment-methods', 'Topup Methods', 'finance-hub'),
  ('topup-system', 'Topup System', 'finance-hub'),
  ('track-recordings', 'Track Recordings', 'content-hub'),
  ('transfer-history', 'Transfer History', 'finance-hub'),
  ('transfer-scheduler', 'Transfer Scheduler', 'finance-hub'),
  ('user-beans-exchange', 'User Beans Exchange', 'finance-hub'),
  ('user-hub', 'User Hub', 'user-hub'),
  ('user-management', 'User Management', 'user-hub'),
  ('user-reports', 'User Reports', 'user-hub'),
  ('users', 'All Users', 'user-hub'),
  ('vehicle-entrances', 'Vehicle Entrances', 'visual-hub'),
  ('verified-badges', 'Verified Badges', 'visual-hub'),
  ('vip-management', 'VIP & Noble System', 'vip-hub'),
  ('vip-medals', 'VIP Medals', 'vip-hub'),
  ('vip-privileges', 'VIP Privileges', 'vip-hub'),
  ('visual-assets', 'Visual Assets Hub', 'visual-hub'),
  ('withdrawals', 'Withdrawals', 'finance-hub')
ON CONFLICT (section_key) DO UPDATE
SET section_name = EXCLUDED.section_name,
    hub_key = EXCLUDED.hub_key;

WITH next_order AS (
  SELECT COALESCE(MAX(display_order), 0) AS base_order FROM public.admin_sections
)
INSERT INTO public.admin_sections (section_key, section_name, hub_key, display_order, is_active)
SELECT fs.section_key, fs.section_name, fs.hub_key, no.base_order + ROW_NUMBER() OVER (ORDER BY fs.section_key), true
FROM tmp_pkg352_frontend_sections fs
CROSS JOIN next_order no
WHERE NOT EXISTS (
  SELECT 1 FROM public.admin_sections s WHERE s.section_key = fs.section_key
);

UPDATE public.admin_sections s
SET is_active = true,
    section_name = COALESCE(NULLIF(s.section_name, ''), fs.section_name),
    hub_key = COALESCE(NULLIF(s.hub_key, ''), fs.hub_key)
FROM tmp_pkg352_frontend_sections fs
WHERE s.section_key = fs.section_key;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.admin_sections TO anon, authenticated;
GRANT ALL ON public.admin_sections TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.admin_section_permissions TO anon, authenticated;
GRANT ALL ON public.admin_section_permissions TO service_role;