INSERT INTO public.app_icon_registry (icon_key, icon_name, category, icon_type, lucide_name, fallback_emoji, color_hex, description, display_order) VALUES
('nav_home', 'Home', 'navigation', 'lucide', 'Home', '🏠', NULL, 'Bottom nav - Home tab', 1),
('nav_party', 'Party', 'navigation', 'lucide', 'PartyPopper', '🎉', NULL, 'Bottom nav - Party rooms tab', 2),
('nav_reels', 'Reels', 'navigation', 'lucide', 'Play', '🎬', NULL, 'Bottom nav - Reels tab', 3),
('nav_live', 'Live', 'navigation', 'lucide', 'Video', '📹', NULL, 'Bottom nav - Live streams tab', 4),
('nav_profile', 'Profile', 'navigation', 'lucide', 'Users', '👤', NULL, 'Bottom nav - Profile tab', 5),
('nav_chat', 'Chat', 'navigation', 'lucide', 'MessageCircle', '💬', NULL, 'Chat page', 6),
('nav_discover', 'Discover', 'navigation', 'lucide', 'Search', '🔍', NULL, 'Discover/Search', 7),
('nav_settings', 'Settings', 'navigation', 'lucide', 'Settings', '⚙️', NULL, 'Settings page', 8),
('nav_back', 'Back', 'navigation', 'lucide', 'ArrowLeft', '←', NULL, 'Back button', 9),
('nav_notifications', 'Notifications', 'navigation', 'lucide', 'Bell', '🔔', NULL, 'Notifications', 10),
('currency_diamond', 'Diamond', 'currency', 'lucide', 'Diamond', '💎', '#00BFFF', 'Diamond currency', 1),
('currency_beans', 'Beans', 'currency', 'lucide', 'Coins', '🫘', '#FFD700', 'Beans currency', 2),
('currency_coin', 'Coin', 'currency', 'lucide', 'Coins', '🪙', '#FFD700', 'Coin currency', 3),
('currency_wallet', 'Wallet', 'currency', 'lucide', 'Wallet', '💰', '#4CAF50', 'Wallet balance', 4),
('currency_dollar', 'Dollar', 'currency', 'lucide', 'DollarSign', '💲', '#4CAF50', 'USD/money', 5),
('currency_gem', 'Gem', 'currency', 'lucide', 'Gem', '💠', '#9C27B0', 'Premium currency', 6),
('feature_gift', 'Gift', 'feature', 'lucide', 'Gift', '🎁', '#FF4081', 'Send gift', 1),
('feature_call', 'Call', 'feature', 'lucide', 'Phone', '📞', '#4CAF50', 'Private call', 2),
('feature_video_call', 'Video Call', 'feature', 'lucide', 'Video', '📹', '#2196F3', 'Video call', 3),
('feature_go_live', 'Go Live', 'feature', 'lucide', 'Video', '🔴', '#F44336', 'Start live stream', 4),
('feature_share', 'Share', 'feature', 'lucide', 'Share2', '📤', NULL, 'Share content', 5),
('feature_follow', 'Follow', 'feature', 'lucide', 'UserPlus', '➕', NULL, 'Follow user', 6),
('feature_leaderboard', 'Leaderboard', 'feature', 'lucide', 'Trophy', '🏆', '#FFD700', 'Rankings', 7),
('feature_recharge', 'Recharge', 'feature', 'lucide', 'CreditCard', '💳', NULL, 'Top-up coins', 8),
('feature_withdrawal', 'Withdrawal', 'feature', 'lucide', 'ArrowUpCircle', '📤', NULL, 'Withdraw earnings', 9),
('feature_face_verify', 'Face Verify', 'feature', 'lucide', 'ScanFace', '🔐', NULL, 'Face verification', 10),
('feature_music', 'Music', 'feature', 'lucide', 'Music', '🎵', NULL, 'Music/audio', 11),
('feature_games', 'Games', 'feature', 'lucide', 'Gamepad2', '🎮', NULL, 'Games section', 12),
('status_live', 'Live', 'status', 'lucide', 'Zap', '🔴', '#F44336', 'User is live', 1),
('status_online', 'Online', 'status', 'lucide', 'Circle', '🟢', '#4CAF50', 'User online', 2),
('status_verified', 'Verified', 'status', 'lucide', 'CheckCircle', '✅', '#2196F3', 'Verified badge', 3),
('status_vip', 'VIP', 'status', 'lucide', 'Crown', '👑', '#FFD700', 'VIP badge', 4),
('status_host', 'Host', 'status', 'lucide', 'Star', '⭐', '#FF9800', 'Host badge', 5),
('status_admin', 'Admin', 'status', 'lucide', 'Shield', '🛡️', '#9C27B0', 'Admin badge', 6),
('social_like', 'Like', 'social', 'lucide', 'Heart', '❤️', '#F44336', 'Like reaction', 1),
('social_comment', 'Comment', 'social', 'lucide', 'MessageCircle', '💬', NULL, 'Comment', 2),
('social_report', 'Report', 'social', 'lucide', 'ShieldAlert', '⚠️', '#FF9800', 'Report', 3),
('social_block', 'Block', 'social', 'lucide', 'Ban', '🚫', '#F44336', 'Block user', 4),
('media_camera', 'Camera', 'media', 'lucide', 'Camera', '📷', NULL, 'Camera', 1),
('media_gallery', 'Gallery', 'media', 'lucide', 'Image', '🖼️', NULL, 'Photo gallery', 2),
('media_play', 'Play', 'media', 'lucide', 'Play', '▶️', NULL, 'Play media', 3),
('media_mic', 'Microphone', 'media', 'lucide', 'Mic', '🎤', NULL, 'Mic on', 4),
('media_mic_off', 'Mic Off', 'media', 'lucide', 'MicOff', '🔇', NULL, 'Mic muted', 5),
('commerce_shop', 'Shop', 'commerce', 'lucide', 'ShoppingBag', '🛍️', NULL, 'Shop', 1),
('commerce_agency', 'Agency', 'commerce', 'lucide', 'Building2', '🏢', NULL, 'Agency', 2),
('commerce_transfer', 'Transfer', 'commerce', 'lucide', 'ArrowRight', '➡️', NULL, 'Transfer', 3),
('reward_daily', 'Daily Reward', 'reward', 'lucide', 'Gift', '🎁', '#FFD700', 'Daily reward', 1),
('reward_task', 'Task', 'reward', 'lucide', 'Target', '🎯', NULL, 'Daily task', 2),
('reward_level', 'Level Up', 'reward', 'lucide', 'TrendingUp', '📈', NULL, 'Level progress', 3),
('reward_achievement', 'Achievement', 'reward', 'lucide', 'Award', '🏅', '#FFD700', 'Achievement', 4)
ON CONFLICT (icon_key) DO NOTHING;