CREATE INDEX IF NOT EXISTS idx_pk_battles_status ON public.pk_battles USING btree (status);
CREATE INDEX IF NOT EXISTS idx_pk_battles_challenger ON public.pk_battles USING btree (challenger_id);
CREATE INDEX IF NOT EXISTS idx_pk_battles_opponent ON public.pk_battles USING btree (opponent_id);
CREATE INDEX IF NOT EXISTS idx_first_recharge_claims_user ON public.first_recharge_claims USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_consumption_return_user ON public.consumption_return_history USING btree (user_id, period_label);
CREATE UNIQUE INDEX IF NOT EXISTS idx_daily_login_claims_unique ON public.daily_login_claims USING btree (user_id, claimed_date);
CREATE INDEX IF NOT EXISTS idx_limited_offer_claims_user ON public.limited_offer_claims USING btree (user_id, offer_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON public.notifications USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_host_applications_status ON public.host_applications USING btree (status);
CREATE INDEX IF NOT EXISTS idx_host_applications_user_id ON public.host_applications USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_host_applications_created_at ON public.host_applications USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_user_id ON public.payment_transactions USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_status ON public.payment_transactions USING btree (status);
CREATE INDEX IF NOT EXISTS idx_payment_gateways_active ON public.payment_gateways USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_password_reset_otps_email ON public.password_reset_otps USING btree (email);
CREATE INDEX IF NOT EXISTS idx_password_reset_otps_expires ON public.password_reset_otps USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_helper_upgrade_requests_helper ON public.helper_upgrade_requests USING btree (helper_id);
CREATE INDEX IF NOT EXISTS idx_helper_upgrade_requests_status ON public.helper_upgrade_requests USING btree (status);
CREATE INDEX IF NOT EXISTS idx_helper_topup_requests_helper ON public.helper_topup_requests USING btree (helper_id);
CREATE INDEX IF NOT EXISTS idx_helper_topup_requests_status ON public.helper_topup_requests USING btree (status);
CREATE INDEX IF NOT EXISTS idx_topup_payment_methods_active ON public.topup_payment_methods USING btree (is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_helper_diamond_packages_level ON public.helper_diamond_packages USING btree (level_number);
CREATE INDEX IF NOT EXISTS idx_game_providers_active ON public.game_providers USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_provider_games_provider ON public.provider_games USING btree (provider_id);
CREATE INDEX IF NOT EXISTS idx_provider_games_active ON public.provider_games USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_game_provider_logs_provider ON public.game_provider_logs USING btree (provider_id);
CREATE INDEX IF NOT EXISTS idx_game_provider_logs_created ON public.game_provider_logs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_channels_country ON public.channels USING btree (country_code);
CREATE INDEX IF NOT EXISTS idx_channels_category ON public.channels USING btree (category);
CREATE INDEX IF NOT EXISTS idx_channels_active ON public.channels USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_live_bans_user_active ON public.live_bans USING btree (user_id, is_active);
CREATE INDEX IF NOT EXISTS idx_live_bans_ban_end ON public.live_bans USING btree (ban_end) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_live_violations_user ON public.live_violations USING btree (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_role_frames_role_type ON public.role_frames USING btree (role_type);
CREATE INDEX IF NOT EXISTS idx_role_frames_active ON public.role_frames USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_user_role_frames_user ON public.user_role_frames USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_user_role_frames_frame ON public.user_role_frames USING btree (frame_id);
CREATE INDEX IF NOT EXISTS idx_user_role_frames_equipped ON public.user_role_frames USING btree (is_equipped);
CREATE INDEX IF NOT EXISTS idx_stream_recordings_host_uid ON public.stream_recordings USING btree (host_uid);
CREATE INDEX IF NOT EXISTS idx_stream_recordings_host_id ON public.stream_recordings USING btree (host_id);
CREATE INDEX IF NOT EXISTS idx_stream_recordings_status ON public.stream_recordings USING btree (status);
CREATE INDEX IF NOT EXISTS idx_stream_recordings_created_at ON public.stream_recordings USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stream_recordings_expires_at ON public.stream_recordings USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_entry_banners_active ON public.entry_banners USING btree (is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_user_entry_banners_user ON public.user_entry_banners USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_entry_name_bars_active ON public.entry_name_bars USING btree (is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_profiles_entry_name_bar ON public.profiles USING btree (equipped_entry_name_bar_id);
CREATE INDEX IF NOT EXISTS idx_device_tokens_user_id ON public.device_tokens USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_device_tokens_active ON public.device_tokens USING btree (is_active) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_support_tickets_user_id ON public.support_tickets USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status ON public.support_tickets USING btree (status);
CREATE INDEX IF NOT EXISTS idx_support_tickets_priority ON public.support_tickets USING btree (priority);
CREATE INDEX IF NOT EXISTS idx_support_tickets_assigned_to ON public.support_tickets USING btree (assigned_to);
CREATE INDEX IF NOT EXISTS idx_support_messages_ticket_id ON public.support_messages USING btree (ticket_id);
CREATE INDEX IF NOT EXISTS idx_support_messages_sender_id ON public.support_messages USING btree (sender_id);
CREATE INDEX IF NOT EXISTS idx_seat_invitations_room_id ON public.seat_invitations USING btree (room_id);
CREATE INDEX IF NOT EXISTS idx_seat_invitations_invitee_id ON public.seat_invitations USING btree (invitee_id);
CREATE INDEX IF NOT EXISTS idx_seat_invitations_status ON public.seat_invitations USING btree (status);
CREATE INDEX IF NOT EXISTS idx_helper_message_replies_message_id ON public.helper_message_replies USING btree (message_id);
CREATE INDEX IF NOT EXISTS idx_helper_message_replies_sender_id ON public.helper_message_replies USING btree (sender_id);
CREATE INDEX IF NOT EXISTS idx_admin_devices_fingerprint ON public.admin_allowed_devices USING btree (device_fingerprint);
CREATE INDEX IF NOT EXISTS idx_admin_devices_admin_user ON public.admin_allowed_devices USING btree (admin_user_id);
CREATE INDEX IF NOT EXISTS idx_admin_devices_status ON public.admin_allowed_devices USING btree (status);
CREATE INDEX IF NOT EXISTS idx_roulette_bets_session ON public.roulette_bets USING btree (session_id);
CREATE INDEX IF NOT EXISTS idx_roulette_bets_user ON public.roulette_bets USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_roulette_sessions_status ON public.roulette_sessions USING btree (status);
CREATE INDEX IF NOT EXISTS idx_user_purchased_backgrounds_user_id ON public.user_purchased_backgrounds USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_user_purchased_backgrounds_background_id ON public.user_purchased_backgrounds USING btree (background_id);
CREATE INDEX IF NOT EXISTS idx_user_beans_exchange_history_user ON public.user_beans_exchange_history USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_user_beans_exchange_tiers_active ON public.user_beans_exchange_tiers USING btree (is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_admin_notices_target ON public.admin_notices USING gin (target_audience);
CREATE INDEX IF NOT EXISTS idx_admin_notices_active ON public.admin_notices USING btree (is_active, expires_at);
CREATE INDEX IF NOT EXISTS idx_admin_notices_created ON public.admin_notices USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_host_contact_violations_host_id ON public.host_contact_violations USING btree (host_id);
CREATE INDEX IF NOT EXISTS idx_host_contact_violations_created_at ON public.host_contact_violations USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_reports_reported_user ON public.user_reports USING btree (reported_user_id);
CREATE INDEX IF NOT EXISTS idx_user_reports_status ON public.user_reports USING btree (status);
CREATE INDEX IF NOT EXISTS idx_user_reports_category ON public.user_reports USING btree (report_category);
CREATE INDEX IF NOT EXISTS idx_user_reports_created ON public.user_reports USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_login_otps_email ON public.admin_login_otps USING btree (email, is_used, expires_at);
CREATE INDEX IF NOT EXISTS idx_vpn_logs_user_id ON public.vpn_detection_logs USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_vpn_logs_is_vpn ON public.vpn_detection_logs USING btree (is_vpn) WHERE (is_vpn = true);
CREATE INDEX IF NOT EXISTS idx_vpn_logs_created_at ON public.vpn_detection_logs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_rate_limit_lookup ON public.rate_limit_attempts USING btree (identifier, action_type, attempted_at DESC);
CREATE INDEX IF NOT EXISTS idx_session_security_user ON public.session_security_logs USING btree (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_session_security_event ON public.session_security_logs USING btree (event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_alerts_type ON public.security_alerts USING btree (alert_type);
CREATE INDEX IF NOT EXISTS idx_security_alerts_severity ON public.security_alerts USING btree (severity) WHERE (is_resolved = false);
CREATE INDEX IF NOT EXISTS idx_security_alerts_created ON public.security_alerts USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_alerts_user ON public.security_alerts USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_login_attempts_identifier ON public.login_attempts USING btree (identifier, attempt_at DESC);
CREATE INDEX IF NOT EXISTS idx_login_attempts_cleanup ON public.login_attempts USING btree (attempt_at);
CREATE INDEX IF NOT EXISTS idx_allowed_external_links_active ON public.allowed_external_links USING btree (is_active) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_allowed_external_links_pattern ON public.allowed_external_links USING btree (url_pattern);
CREATE INDEX IF NOT EXISTS idx_recovery_tokens_token ON public.recovery_tokens USING btree (token) WHERE (is_used = false);
CREATE INDEX IF NOT EXISTS idx_recovery_tokens_device ON public.recovery_tokens USING btree (device_id);
CREATE INDEX IF NOT EXISTS idx_live_face_violations_host ON public.live_face_violations USING btree (host_id);
CREATE INDEX IF NOT EXISTS idx_live_face_violations_created ON public.live_face_violations USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_live_face_violations_reviewed ON public.live_face_violations USING btree (admin_reviewed);
CREATE INDEX IF NOT EXISTS idx_host_conversion_requests_status ON public.host_conversion_requests USING btree (status);
CREATE INDEX IF NOT EXISTS idx_host_conversion_requests_user_id ON public.host_conversion_requests USING btree (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_rating_reward_claims_user ON public.rating_reward_claims USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_email_otps_email_purpose ON public.email_otps USING btree (email, purpose, is_used, expires_at);
CREATE INDEX IF NOT EXISTS idx_email_otps_expires ON public.email_otps USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_beauty_filters_active ON public.beauty_filters USING btree (is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_beauty_filters_category ON public.beauty_filters USING btree (category);
CREATE INDEX IF NOT EXISTS idx_ar_stickers_active ON public.ar_stickers USING btree (is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_ar_stickers_category ON public.ar_stickers USING btree (category);
CREATE INDEX IF NOT EXISTS idx_reconciliation_user ON public.payment_reconciliation_log USING btree (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reconciliation_gateway ON public.payment_reconciliation_log USING btree (gateway, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reconciliation_event ON public.payment_reconciliation_log USING btree (event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reconciliation_order ON public.payment_reconciliation_log USING btree (order_id);
CREATE INDEX IF NOT EXISTS idx_icon_registry_category ON public.app_icon_registry USING btree (category);
CREATE INDEX IF NOT EXISTS idx_icon_registry_key ON public.app_icon_registry USING btree (icon_key);
CREATE INDEX IF NOT EXISTS idx_user_parcels_user ON public.user_parcels USING btree (user_id, status);
CREATE INDEX IF NOT EXISTS idx_user_parcels_expires ON public.user_parcels USING btree (expires_at) WHERE (status <> 'expired'::text);
CREATE INDEX IF NOT EXISTS idx_parcel_claims_user ON public.parcel_claims USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_admin_music_active ON public.admin_music_library USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_admin_music_category ON public.admin_music_library USING btree (category);
CREATE INDEX IF NOT EXISTS idx_agencies_is_active ON public.agencies USING btree (is_active) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_agencies_is_blocked ON public.agencies USING btree (is_blocked) WHERE (is_blocked = true);
CREATE INDEX IF NOT EXISTS idx_agencies_owner ON public.agencies USING btree (owner_id);
CREATE INDEX IF NOT EXISTS idx_agencies_parent_agency_id ON public.agencies USING btree (parent_agency_id);
CREATE INDEX IF NOT EXISTS idx_agency_commission_history_agency ON public.agency_commission_history USING btree (agency_id);
CREATE INDEX IF NOT EXISTS idx_agency_commission_history_created ON public.agency_commission_history USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agency_commission_history_host ON public.agency_commission_history USING btree (host_id);
CREATE INDEX IF NOT EXISTS idx_agency_diamond_transactions_agency_id ON public.agency_diamond_transactions USING btree (agency_id);
CREATE INDEX IF NOT EXISTS idx_agency_diamond_transactions_created_at ON public.agency_diamond_transactions USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agency_hosts_agency ON public.agency_hosts USING btree (agency_id, status);
CREATE INDEX IF NOT EXISTS idx_agency_hosts_host ON public.agency_hosts USING btree (host_id);
CREATE INDEX IF NOT EXISTS idx_agency_withdrawals_country ON public.agency_withdrawals USING btree (country_code);
CREATE INDEX IF NOT EXISTS idx_agency_withdrawals_helper ON public.agency_withdrawals USING btree (assigned_helper_id);
CREATE INDEX IF NOT EXISTS idx_app_event_themes_country_active ON public.app_event_themes USING btree (country_code, is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_app_event_themes_country_code ON public.app_event_themes USING btree (country_code);
CREATE INDEX IF NOT EXISTS idx_avatar_frames_active ON public.avatar_frames USING btree (is_active) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_avatar_frames_category ON public.avatar_frames USING btree (category);
CREATE INDEX IF NOT EXISTS idx_avatar_frames_type ON public.avatar_frames USING btree (frame_type);
CREATE INDEX IF NOT EXISTS idx_blocked_ips_address ON public.blocked_ips USING btree (ip_address);
CREATE INDEX IF NOT EXISTS idx_channels_featured ON public.channels USING btree (is_featured) WHERE (is_featured = true);
CREATE INDEX IF NOT EXISTS idx_channels_is_premium ON public.channels USING btree (is_premium);
CREATE INDEX IF NOT EXISTS idx_coin_transfers_receiver ON public.coin_transfers USING btree (receiver_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_coin_transfers_sender ON public.coin_transfers USING btree (sender_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_conv_encryption_keys_lookup ON public.conversation_encryption_keys USING btree (conversation_id, user_id);
CREATE INDEX IF NOT EXISTS idx_conversations_last_message ON public.conversations USING btree (last_message_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversations_participant_1 ON public.conversations USING btree (participant_1);
CREATE INDEX IF NOT EXISTS idx_conversations_participant_2 ON public.conversations USING btree (participant_2);
CREATE INDEX IF NOT EXISTS idx_daily_login_claims_date ON public.daily_login_claims USING btree (claimed_date);
CREATE INDEX IF NOT EXISTS idx_device_tokens_token ON public.device_tokens USING btree (token);
CREATE INDEX IF NOT EXISTS idx_entertainment_featured ON public.entertainment USING btree (is_featured) WHERE (is_featured = true);
CREATE INDEX IF NOT EXISTS idx_error_logs_created_at ON public.system_error_logs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_error_logs_is_resolved ON public.system_error_logs USING btree (is_resolved);
CREATE INDEX IF NOT EXISTS idx_error_logs_page_path ON public.system_error_logs USING btree (page_path);
CREATE INDEX IF NOT EXISTS idx_face_records_embedding ON public.face_records USING btree (face_embedding);
CREATE INDEX IF NOT EXISTS idx_face_verification_duplicate ON public.face_verification_submissions USING btree (is_duplicate_face) WHERE (is_duplicate_face = true);
CREATE INDEX IF NOT EXISTS idx_failed_logins_email ON public.failed_login_attempts USING btree (email, last_attempt_at);
CREATE INDEX IF NOT EXISTS idx_followers_follower ON public.followers USING btree (follower_id);
CREATE INDEX IF NOT EXISTS idx_followers_following ON public.followers USING btree (following_id);
CREATE INDEX IF NOT EXISTS idx_game_bets_user ON public.game_bets USING btree (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_game_transactions_created_at ON public.game_transactions USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_game_transactions_game_id ON public.game_transactions USING btree (game_id);
CREATE INDEX IF NOT EXISTS idx_game_transactions_user_id ON public.game_transactions USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_gift_transaction_logs_created_at ON public.gift_transaction_logs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gift_transaction_logs_receiver ON public.gift_transaction_logs USING btree (receiver_id);
CREATE INDEX IF NOT EXISTS idx_gift_transaction_logs_status ON public.gift_transaction_logs USING btree (status);
CREATE INDEX IF NOT EXISTS idx_gift_transactions_created ON public.gift_transactions USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_gift_transactions_created_at ON public.gift_transactions USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gift_transactions_party_room_id ON public.gift_transactions USING btree (party_room_id) WHERE (party_room_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_gift_transactions_receiver ON public.gift_transactions USING btree (receiver_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gift_transactions_reel_id ON public.gift_transactions USING btree (reel_id) WHERE (reel_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_gift_transactions_sender ON public.gift_transactions USING btree (sender_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gifts_category ON public.gifts USING btree (category);
CREATE INDEX IF NOT EXISTS idx_gifts_display_order ON public.gifts USING btree (display_order);
CREATE INDEX IF NOT EXISTS idx_group_messages_encrypted ON public.group_messages USING btree (is_encrypted) WHERE (is_encrypted = true);
CREATE INDEX IF NOT EXISTS idx_helper_admin_messages_created_at ON public.helper_admin_messages USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_helper_admin_messages_helper_id ON public.helper_admin_messages USING btree (helper_id);
CREATE INDEX IF NOT EXISTS idx_helper_admin_messages_is_read ON public.helper_admin_messages USING btree (is_read);
CREATE INDEX IF NOT EXISTS idx_helper_applications_status ON public.helper_applications USING btree (status);
CREATE INDEX IF NOT EXISTS idx_helper_applications_user_id ON public.helper_applications USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_helper_notifications_helper ON public.helper_notifications USING btree (helper_id);
CREATE INDEX IF NOT EXISTS idx_helper_notifications_unread ON public.helper_notifications USING btree (helper_id, is_read);
CREATE INDEX IF NOT EXISTS idx_helper_orders_helper ON public.helper_orders USING btree (helper_id);
CREATE INDEX IF NOT EXISTS idx_helper_orders_status ON public.helper_orders USING btree (status);
CREATE INDEX IF NOT EXISTS idx_helper_orders_user ON public.helper_orders USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_helper_payment_methods_country ON public.helper_payment_methods USING btree (country_code);
CREATE INDEX IF NOT EXISTS idx_helper_payment_methods_helper ON public.helper_payment_methods USING btree (helper_id);
CREATE INDEX IF NOT EXISTS idx_helper_transactions_helper ON public.helper_transactions USING btree (helper_id);
CREATE INDEX IF NOT EXISTS idx_helper_transactions_status ON public.helper_transactions USING btree (status);
CREATE INDEX IF NOT EXISTS idx_helper_withdrawal_requests_helper ON public.helper_withdrawal_requests USING btree (helper_id);
CREATE INDEX IF NOT EXISTS idx_helper_withdrawal_requests_status ON public.helper_withdrawal_requests USING btree (status);
CREATE INDEX IF NOT EXISTS idx_host_applications_pending ON public.host_applications USING btree (status) WHERE (status = 'pending'::text);
CREATE INDEX IF NOT EXISTS idx_kids_content_featured ON public.kids_content USING btree (is_featured) WHERE (is_featured = true);
CREATE UNIQUE INDEX IF NOT EXISTS idx_leaderboard_reward_history_unique ON public.leaderboard_reward_history USING btree (user_id, category, period_type, period_label);
CREATE INDEX IF NOT EXISTS idx_live_game_bets_round ON public.live_game_bets USING btree (round_id);
CREATE INDEX IF NOT EXISTS idx_live_game_rounds_game_status ON public.live_game_rounds USING btree (game_id, status);
CREATE INDEX IF NOT EXISTS idx_live_game_rounds_global ON public.live_game_rounds USING btree (game_id) WHERE (room_id IS NULL);
CREATE INDEX IF NOT EXISTS idx_live_streams_active ON public.live_streams USING btree (is_active) WHERE ((is_active = true) AND (ended_at IS NULL));
CREATE INDEX IF NOT EXISTS idx_live_streams_active_heartbeat ON public.live_streams USING btree (is_active, last_heartbeat) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_live_streams_music_playing ON public.live_streams USING btree (music_playing) WHERE (music_playing = true);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON public.messages USING btree (conversation_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_sender ON public.messages USING btree (conversation_id, sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_encrypted ON public.messages USING btree (is_encrypted) WHERE (is_encrypted = true);
CREATE INDEX IF NOT EXISTS idx_messages_is_read ON public.messages USING btree (is_read) WHERE (is_read = false);
CREATE INDEX IF NOT EXISTS idx_messages_status ON public.messages USING btree (conversation_id, status) WHERE (status <> 'read'::text);
CREATE INDEX IF NOT EXISTS idx_moderation_logs_created_at ON public.chat_moderation_logs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_moderation_logs_user_id ON public.chat_moderation_logs USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_moderation_logs_violation_type ON public.chat_moderation_logs USING btree (violation_type);
CREATE INDEX IF NOT EXISTS idx_movies_featured ON public.movies USING btree (is_featured) WHERE (is_featured = true);
CREATE INDEX IF NOT EXISTS idx_movies_is_premium ON public.movies USING btree (is_premium);
CREATE INDEX IF NOT EXISTS idx_music_featured ON public.music USING btree (is_featured) WHERE (is_featured = true);
CREATE INDEX IF NOT EXISTS idx_new_host_bonus_progress_user_date ON public.new_host_live_bonus_progress USING btree (user_id, bonus_date);
CREATE INDEX IF NOT EXISTS idx_news_featured ON public.news USING btree (is_featured) WHERE (is_featured = true);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON public.notifications USING btree (user_id, is_read) WHERE (is_read = false);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON public.notifications USING btree (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_party_room_messages_created_at ON public.party_room_messages USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_party_room_messages_room_id ON public.party_room_messages USING btree (room_id);
CREATE INDEX IF NOT EXISTS idx_party_rooms_active ON public.party_rooms USING btree (is_active) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_party_rooms_music_playing ON public.party_rooms USING btree (music_playing) WHERE (music_playing = true);
CREATE INDEX IF NOT EXISTS idx_payroll_requests_agency_id ON public.payroll_requests USING btree (agency_id);
CREATE INDEX IF NOT EXISTS idx_payroll_requests_status ON public.payroll_requests USING btree (status);
CREATE INDEX IF NOT EXISTS idx_phone_otps_expires ON public.phone_otps USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_phone_otps_phone ON public.phone_otps USING btree (phone_number, is_used);
CREATE INDEX IF NOT EXISTS idx_pk_competitions_status ON public.pk_competitions USING btree (status, end_date);
CREATE INDEX IF NOT EXISTS idx_pk_participants_competition ON public.pk_participants USING btree (competition_id, score DESC);
CREATE INDEX IF NOT EXISTS idx_pk_participants_user ON public.pk_participants USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_poster_images_user_id ON public.poster_images USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_private_calls_created ON public.private_calls USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_private_calls_created_at ON public.private_calls USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_private_calls_earnings_not_credited ON public.private_calls USING btree (host_id, host_earnings_credited) WHERE ((host_earnings_credited = false) AND (status = 'ended'::text));
CREATE INDEX IF NOT EXISTS idx_profiles_app_uid ON public.profiles USING btree (app_uid);
CREATE INDEX IF NOT EXISTS idx_profiles_created_at ON public.profiles USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_profiles_deletion ON public.profiles USING btree (deletion_scheduled_at) WHERE (deletion_scheduled_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_profiles_device_id ON public.profiles USING btree (device_id) WHERE (device_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_profiles_face_hash ON public.profiles USING btree (face_hash) WHERE (face_hash IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_profiles_is_blocked ON public.profiles USING btree (is_blocked) WHERE (is_blocked = true);
CREATE INDEX IF NOT EXISTS idx_profiles_is_host ON public.profiles USING btree (is_host) WHERE (is_host = true);
CREATE INDEX IF NOT EXISTS idx_profiles_is_online ON public.profiles USING btree (is_online) WHERE (is_online = true);
CREATE INDEX IF NOT EXISTS idx_profiles_online_status ON public.profiles USING btree (is_online, last_seen_at) WHERE (is_online = true);
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_unique_device_id ON public.profiles USING btree (device_id) WHERE ((device_id IS NOT NULL) AND (is_deleted = false));
CREATE INDEX IF NOT EXISTS idx_rate_limits_user_endpoint ON public.rate_limits USING btree (user_id, endpoint, window_start);
CREATE INDEX IF NOT EXISTS idx_recharge_agency ON public.recharge_transactions USING btree (agency_id);
CREATE INDEX IF NOT EXISTS idx_recharge_purchase_source ON public.recharge_transactions USING btree (purchase_source);
CREATE INDEX IF NOT EXISTS idx_recharge_transactions_created ON public.recharge_transactions USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_recharge_transactions_created_at ON public.recharge_transactions USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_recharge_user ON public.recharge_transactions USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_reels_sound_title ON public.reels USING btree (sound_title);
CREATE INDEX IF NOT EXISTS idx_seat_requests_room_id ON public.seat_requests USING btree (room_id);
CREATE INDEX IF NOT EXISTS idx_seat_requests_status ON public.seat_requests USING btree (status);
CREATE INDEX IF NOT EXISTS idx_security_audit_action ON public.security_audit_log USING btree (action, created_at);
CREATE INDEX IF NOT EXISTS idx_security_audit_user ON public.security_audit_log USING btree (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_session_security_logs_created_at ON public.session_security_logs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_shop_items_category ON public.shop_items USING btree (category);
CREATE INDEX IF NOT EXISTS idx_shop_items_featured ON public.shop_items USING btree (is_featured);
CREATE INDEX IF NOT EXISTS idx_sports_featured ON public.sports USING btree (is_featured) WHERE (is_featured = true);
CREATE INDEX IF NOT EXISTS idx_sub_agent_commissions_sub_agent ON public.sub_agent_commissions USING btree (sub_agent_id);
CREATE INDEX IF NOT EXISTS idx_sub_agent_referrals_sub_agent ON public.sub_agent_referrals USING btree (sub_agent_id);
CREATE INDEX IF NOT EXISTS idx_sub_agents_agency ON public.sub_agents USING btree (agency_id);
CREATE INDEX IF NOT EXISTS idx_sub_agents_user ON public.sub_agents USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_system_error_logs_created_at ON public.system_error_logs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_topup_helpers_active ON public.topup_helpers USING btree (is_active, is_verified);
CREATE INDEX IF NOT EXISTS idx_topup_helpers_country ON public.topup_helpers USING btree (country_code);
CREATE INDEX IF NOT EXISTS idx_topup_helpers_supported_countries ON public.topup_helpers USING gin (supported_countries);
CREATE INDEX IF NOT EXISTS idx_user_purchases_active ON public.user_purchases USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_user_purchases_user ON public.user_purchases USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_status ON public.user_subscriptions USING btree (status);
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_user_id ON public.user_subscriptions USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_user_vip_subscriptions_expires_at ON public.user_vip_subscriptions USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_user_vip_subscriptions_user_id ON public.user_vip_subscriptions USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_vip_exclusive_items_tier ON public.vip_exclusive_items USING btree (vip_tier_id);
CREATE INDEX IF NOT EXISTS idx_vip_exclusive_items_type ON public.vip_exclusive_items USING btree (item_type);
CREATE UNIQUE INDEX IF NOT EXISTS leaderboard_reward_history_agency_period_unique ON public.leaderboard_reward_history USING btree (agency_id, category, period_type, period_label) WHERE (agency_id IS NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS leaderboard_reward_history_user_period_unique ON public.leaderboard_reward_history USING btree (user_id, category, period_type, period_label) WHERE (user_id IS NOT NULL);