
-- Add category column to notification_templates
ALTER TABLE public.notification_templates ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'system';

-- Insert Push Broadcast templates - Host Messages
INSERT INTO public.notification_templates (template_key, title_template, message_template, description, category) VALUES
('push_host_1', '🌟 Host Account Activated! 🎤✨', '🎉 Congratulations! Your account has been upgraded to Host status! 🔥 Complete your Face Verification now and start going live to earn rewards! 💎🫘 Welcome to the spotlight! 🌟', 'Host activation notification', 'push_host'),
('push_host_2', '🔴 Go Live Now & Earn Big! 💰🎤', '🎤 Your Host privileges are active! Start streaming today and earn 💎 Diamonds & 🫘 Beans from gifts! The more you stream, the more you earn! 🔥 Go live now!', 'Go live reminder for hosts', 'push_host'),
('push_host_3', '⚠️ Complete Your Verification 🪪📸', '📸 Your Host face verification is pending! Complete it now to unlock full streaming privileges and start earning rewards! ⏰ Don''t miss out! 🚀', 'Verification reminder', 'push_host'),
('push_host_4', '🏆 Host Performance Bonus! 🎁💎', '🎉 Great streaming this week! Your performance has earned you bonus rewards! 💎 Keep going live and climb the rankings! 🏆 Top hosts earn exclusive prizes! 🌟', 'Performance bonus notification', 'push_host'),
('push_host_5', '📢 New Host Guidelines Update 📋✨', '📋 Important update for all hosts! New streaming guidelines are now in effect. Please review them in your Host Dashboard to ensure uninterrupted streaming! ✅', 'Host guidelines update', 'push_host'),

-- Push Broadcast templates - Inviter Rewards
('push_inviter_1', '🎉 Invitation Reward Earned! 💰🎁', '💎 Your friend just joined using your invite code! You''ve earned bonus Diamonds as a reward! 🎁 Keep inviting friends to earn more! Share your code now! 🚀', 'Invitation reward earned', 'push_inviter'),
('push_inviter_2', '🚀 Double Invite Rewards! 2x💎🔥', '🔥 LIMITED TIME! Earn DOUBLE rewards for every friend you invite this week! Share your invite code now and maximize your earnings! 💎💎 Don''t miss out! ⏰', 'Double invite rewards promo', 'push_inviter'),
('push_inviter_3', '👥 Your Invite Network is Growing! 📈', '📈 Amazing! Your invited friends are actively using the app! You''re earning passive rewards from their activity! 💰 Keep building your network! 🌟', 'Invite network growth', 'push_inviter'),
('push_inviter_4', '🏅 Top Inviter Badge Unlocked! 🎖️', '🎖️ Congratulations! You''ve reached Top Inviter status! Enjoy exclusive badge, higher rewards, and special privileges! 👑 Keep sharing to maintain your rank!', 'Top inviter badge', 'push_inviter'),
('push_inviter_5', '💡 Share & Earn — It''s Easy! 🤝💎', '🤝 Did you know? Every friend you invite earns you 💎 Diamonds! Simply share your unique invite code and watch your rewards grow! Start sharing now! 📲', 'Share and earn reminder', 'push_inviter'),

-- Push Broadcast templates - Live Rewards
('push_live_1', '⏰ 5-Hour Live Milestone! 🎉🏆', '🏆 You''ve completed 5 hours of live streaming this week! 🎉 Claim your milestone reward now! 💎 Keep streaming to unlock even bigger prizes! 🔥', '5-hour live milestone', 'push_live'),
('push_live_2', '🔥 Stream More, Earn More! 💎📈', '📈 You''re on fire! Complete your daily streaming target to earn bonus 💎 Diamonds! Every hour counts towards your weekly milestone! ⏰ Go live now! 🎤', 'Stream more earn more', 'push_live'),
('push_live_3', '🎁 Weekly Streaming Bonus Ready! 🎉', '🎉 Your weekly streaming rewards are ready to claim! 💎 Visit your Host Dashboard to collect your earned Diamonds and Beans! 🫘 Don''t forget to claim! ⏰', 'Weekly streaming bonus', 'push_live'),
('push_live_4', '🌟 Golden Hour — 3x Earnings! ⚡💰', '⚡ GOLDEN HOUR is LIVE! Stream in the next 2 hours to earn 3x rewards! 💰 This is your chance to maximize earnings! 🎤 Go live NOW! 🔥', 'Golden hour promo', 'push_live'),
('push_live_5', '📊 Your Streaming Stats This Week 📈', '📊 Weekly Summary: Check your streaming hours, gifts received, and total earnings! 📈 Visit your Dashboard to see your performance and set new goals! 🎯 Keep climbing! 🚀', 'Weekly streaming stats', 'push_live'),

-- Email Broadcast templates
('email_announcement', '📢 General Announcement', '<div style="font-family: -apple-system, BlinkMacSystemFont, ''Segoe UI'', Roboto, sans-serif; max-width: 600px; margin: 0 auto; background: #0a0a12; color: #fff; border-radius: 16px; overflow: hidden;"><div style="background: linear-gradient(135deg, #9333ea, #ec4899, #f97316); padding: 32px; text-align: center;"><img src="https://merilive.com/images/merilive-logo.jpg" alt="MeriLive" width="120" style="border-radius: 50%;" /><h1 style="margin: 16px 0 0; font-size: 24px; color: #fff;">MeriLive Update</h1></div><div style="padding: 32px;"><p style="color: #e0e0e0; line-height: 1.6;">Hello! 👋</p><p style="color: #b0b0b0; line-height: 1.6;">We have an exciting update for you...</p><p style="color: #b0b0b0; line-height: 1.6; margin-top: 24px;">— Team MeriLive ❤️</p></div></div>', 'General announcement email template', 'email'),
('email_new_feature', '🎉 New Feature', '<div style="font-family: -apple-system, BlinkMacSystemFont, ''Segoe UI'', Roboto, sans-serif; max-width: 600px; margin: 0 auto; background: #0a0a12; color: #fff; border-radius: 16px; overflow: hidden;"><div style="background: linear-gradient(135deg, #6366f1, #8b5cf6, #a855f7); padding: 32px; text-align: center;"><h1 style="margin: 0; font-size: 28px; color: #fff;">🚀 New Feature Alert!</h1><p style="color: rgba(255,255,255,0.8); margin-top: 8px;">Something amazing is here</p></div><div style="padding: 32px;"><p style="color: #e0e0e0; line-height: 1.6;">We''re excited to introduce...</p><a href="https://merilive.com" style="display: inline-block; margin-top: 24px; padding: 14px 32px; background: linear-gradient(135deg, #9333ea, #ec4899); color: #fff; text-decoration: none; border-radius: 12px; font-weight: bold;">Open MeriLive</a></div></div>', 'New feature announcement email', 'email'),
('email_maintenance', '⚠️ Maintenance Notice', '<div style="font-family: -apple-system, BlinkMacSystemFont, ''Segoe UI'', Roboto, sans-serif; max-width: 600px; margin: 0 auto; background: #0a0a12; color: #fff; border-radius: 16px; overflow: hidden;"><div style="background: linear-gradient(135deg, #f59e0b, #ef4444); padding: 32px; text-align: center;"><h1 style="margin: 0; font-size: 24px; color: #fff;">⚠️ Maintenance Notice</h1></div><div style="padding: 32px;"><p style="color: #e0e0e0; line-height: 1.6;">We will be performing scheduled maintenance on...</p><div style="background: rgba(245,158,11,0.1); border: 1px solid rgba(245,158,11,0.3); border-radius: 12px; padding: 16px; margin-top: 16px;"><p style="color: #fbbf24; margin: 0;"><strong>Duration:</strong> ~2 hours</p><p style="color: #fbbf24; margin: 8px 0 0;"><strong>Time:</strong> TBD</p></div><p style="color: #b0b0b0; margin-top: 24px;">Thank you for your patience! 🙏</p></div></div>', 'Maintenance notice email', 'email')

ON CONFLICT (template_key) DO NOTHING;
