DROP POLICY IF EXISTS "Admin can manage bonus settings" ON public.new_host_live_bonus_settings;
CREATE POLICY "Admin can manage bonus settings" ON public.new_host_live_bonus_settings TO authenticated USING ((EXISTS ( SELECT 1 FROM public.admin_users WHERE ((admin_users.user_id = auth.uid()) AND (admin_users.is_active = true))))) WITH CHECK ((EXISTS ( SELECT 1 FROM public.admin_users WHERE ((admin_users.user_id = auth.uid()) AND (admin_users.is_active = true)))));
DROP POLICY IF EXISTS "Admin can read all bonus progress" ON public.new_host_live_bonus_progress;
CREATE POLICY "Admin can read all bonus progress" ON public.new_host_live_bonus_progress FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM public.admin_users WHERE ((admin_users.user_id = auth.uid()) AND (admin_users.is_active = true)))));
DROP POLICY IF EXISTS "Admin can view all claims" ON public.parcel_claims;
CREATE POLICY "Admin can view all claims" ON public.parcel_claims FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM public.admin_users WHERE ((admin_users.user_id = auth.uid()) AND (admin_users.is_active = true)))));
DROP POLICY IF EXISTS "Admin can view all parcels" ON public.user_parcels;
CREATE POLICY "Admin can view all parcels" ON public.user_parcels FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM public.admin_users WHERE ((admin_users.user_id = auth.uid()) AND (admin_users.is_active = true)))));
DROP POLICY IF EXISTS "Admin can view all private calls" ON public.private_calls;
CREATE POLICY "Admin can view all private calls" ON public.private_calls FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1 FROM public.admin_users WHERE ((admin_users.user_id = auth.uid()) AND (admin_users.is_active = true)))));
DROP POLICY IF EXISTS "Admin full access ar_stickers" ON public.ar_stickers;
CREATE POLICY "Admin full access ar_stickers" ON public.ar_stickers USING ((EXISTS ( SELECT 1 FROM public.admin_users WHERE ((admin_users.user_id = auth.uid()) AND (admin_users.is_active = true)))));
DROP POLICY IF EXISTS "Admin full access beauty_filters" ON public.beauty_filters;
CREATE POLICY "Admin full access beauty_filters" ON public.beauty_filters USING ((EXISTS ( SELECT 1 FROM public.admin_users WHERE ((admin_users.user_id = auth.uid()) AND (admin_users.is_active = true)))));
DROP POLICY IF EXISTS "Admin full access game_configs" ON public.game_configs;
CREATE POLICY "Admin full access game_configs" ON public.game_configs USING ((EXISTS ( SELECT 1 FROM public.admin_users WHERE ((admin_users.user_id = auth.uid()) AND (admin_users.is_active = true)))));
DROP POLICY IF EXISTS "Admin full access to parcel templates" ON public.parcel_templates;
CREATE POLICY "Admin full access to parcel templates" ON public.parcel_templates TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Admin users can delete entry banners" ON public.entry_banners;
CREATE POLICY "Admin users can delete entry banners" ON public.entry_banners FOR DELETE TO authenticated USING ((EXISTS ( SELECT 1 FROM public.admin_users au WHERE ((au.user_id = auth.uid()) AND (au.is_active = true)))));
DROP POLICY IF EXISTS "Admin users can delete party room backgrounds" ON public.party_room_backgrounds;
CREATE POLICY "Admin users can delete party room backgrounds" ON public.party_room_backgrounds FOR DELETE TO authenticated USING ((auth.uid() IN ( SELECT au.user_id FROM public.admin_users au WHERE ((au.user_id = auth.uid()) AND (au.is_active = true)))));
DROP POLICY IF EXISTS "Admin users can insert entry banners" ON public.entry_banners;
CREATE POLICY "Admin users can insert entry banners" ON public.entry_banners FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1 FROM public.admin_users au WHERE ((au.user_id = auth.uid()) AND (au.is_active = true)))));
DROP POLICY IF EXISTS "Admin users can insert party room backgrounds" ON public.party_room_backgrounds;
CREATE POLICY "Admin users can insert party room backgrounds" ON public.party_room_backgrounds FOR INSERT TO authenticated WITH CHECK ((auth.uid() IN ( SELECT au.user_id FROM public.admin_users au WHERE ((au.user_id = auth.uid()) AND (au.is_active = true)))));
DROP POLICY IF EXISTS "Admin users can update any party room" ON public.party_rooms;
CREATE POLICY "Admin users can update any party room" ON public.party_rooms FOR UPDATE TO authenticated USING ((auth.uid() IN ( SELECT au.user_id FROM public.admin_users au WHERE ((au.user_id = auth.uid()) AND (au.is_active = true)))));
DROP POLICY IF EXISTS "Admin users can update entry banners" ON public.entry_banners;
CREATE POLICY "Admin users can update entry banners" ON public.entry_banners FOR UPDATE TO authenticated USING ((EXISTS ( SELECT 1 FROM public.admin_users au WHERE ((au.user_id = auth.uid()) AND (au.is_active = true)))));
DROP POLICY IF EXISTS "Admin users can update party room backgrounds" ON public.party_room_backgrounds;
CREATE POLICY "Admin users can update party room backgrounds" ON public.party_room_backgrounds FOR UPDATE TO authenticated USING ((auth.uid() IN ( SELECT au.user_id FROM public.admin_users au WHERE ((au.user_id = auth.uid()) AND (au.is_active = true)))));
DROP POLICY IF EXISTS "Admin users can view all party room backgrounds" ON public.party_room_backgrounds;
CREATE POLICY "Admin users can view all party room backgrounds" ON public.party_room_backgrounds FOR SELECT TO authenticated USING ((auth.uid() IN ( SELECT au.user_id FROM public.admin_users au WHERE ((au.user_id = auth.uid()) AND (au.is_active = true)))));
DROP POLICY IF EXISTS "Admin users can view all party rooms" ON public.party_rooms;
CREATE POLICY "Admin users can view all party rooms" ON public.party_rooms FOR SELECT TO authenticated USING ((auth.uid() IN ( SELECT au.user_id FROM public.admin_users au WHERE ((au.user_id = auth.uid()) AND (au.is_active = true)))));
DROP POLICY IF EXISTS "Admin users can view all task progress" ON public.user_task_progress;
CREATE POLICY "Admin users can view all task progress" ON public.user_task_progress FOR SELECT USING ((EXISTS ( SELECT 1 FROM public.admin_users WHERE ((admin_users.user_id = auth.uid()) AND (admin_users.is_active = true)))));
DROP POLICY IF EXISTS "Admin view all game transactions" ON public.game_transactions;
CREATE POLICY "Admin view all game transactions" ON public.game_transactions FOR SELECT USING ((EXISTS ( SELECT 1 FROM public.admin_users WHERE ((admin_users.user_id = auth.uid()) AND (admin_users.is_active = true)))));
DROP POLICY IF EXISTS "Admins can add hosts to agencies" ON public.agency_hosts;
CREATE POLICY "Admins can add hosts to agencies" ON public.agency_hosts FOR INSERT TO authenticated WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "Admins can create logs" ON public.admin_logs;
CREATE POLICY "Admins can create logs" ON public.admin_logs FOR INSERT TO authenticated WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "Admins can create replies" ON public.helper_message_replies;
CREATE POLICY "Admins can create replies" ON public.helper_message_replies FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1 FROM public.user_roles WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = 'admin'::text)))));
DROP POLICY IF EXISTS "Admins can delete any stream" ON public.live_streams;
CREATE POLICY "Admins can delete any stream" ON public.live_streams FOR DELETE TO authenticated USING ((EXISTS ( SELECT 1 FROM public.admin_users WHERE ((admin_users.user_id = auth.uid()) AND (admin_users.is_active = true)))));
DROP POLICY IF EXISTS "Admins can delete error logs" ON public.system_error_logs;
CREATE POLICY "Admins can delete error logs" ON public.system_error_logs FOR DELETE TO authenticated USING (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "Admins can delete gifts" ON public.gifts;
CREATE POLICY "Admins can delete gifts" ON public.gifts FOR DELETE TO authenticated USING (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "Admins can delete helpers" ON public.topup_helpers;
CREATE POLICY "Admins can delete helpers" ON public.topup_helpers FOR DELETE TO authenticated USING ((public.is_real_user() AND public.is_admin(auth.uid())));
DROP POLICY IF EXISTS "Admins can delete trader level tiers" ON public.trader_level_tiers;
CREATE POLICY "Admins can delete trader level tiers" ON public.trader_level_tiers FOR DELETE TO authenticated USING (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "Admins can delete user level tiers" ON public.user_level_tiers;
CREATE POLICY "Admins can delete user level tiers" ON public.user_level_tiers FOR DELETE TO authenticated USING (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "Admins can insert branding settings" ON public.branding_settings;
CREATE POLICY "Admins can insert branding settings" ON public.branding_settings FOR INSERT TO authenticated WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "Admins can insert gift logs" ON public.gift_transaction_logs;
CREATE POLICY "Admins can insert gift logs" ON public.gift_transaction_logs FOR INSERT TO authenticated WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "Admins can insert gifts" ON public.gifts;
CREATE POLICY "Admins can insert gifts" ON public.gifts FOR INSERT TO authenticated WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "Admins can insert helpers" ON public.topup_helpers;
CREATE POLICY "Admins can insert helpers" ON public.topup_helpers FOR INSERT TO authenticated WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "Admins can insert reward history" ON public.leaderboard_reward_history;
CREATE POLICY "Admins can insert reward history" ON public.leaderboard_reward_history FOR INSERT TO authenticated WITH CHECK ((EXISTS ( SELECT 1 FROM public.admin_users WHERE ((admin_users.user_id = auth.uid()) AND (admin_users.is_active = true)))));
DROP POLICY IF EXISTS "Admins can insert trader level tiers" ON public.trader_level_tiers;
CREATE POLICY "Admins can insert trader level tiers" ON public.trader_level_tiers FOR INSERT TO authenticated WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "Admins can insert user level tiers" ON public.user_level_tiers;
CREATE POLICY "Admins can insert user level tiers" ON public.user_level_tiers FOR INSERT TO authenticated WITH CHECK (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "Admins can manage agency level tiers" ON public.agency_level_tiers;
CREATE POLICY "Admins can manage agency level tiers" ON public.agency_level_tiers USING (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "Admins can manage agency-host relationships" ON public.agency_hosts;
CREATE POLICY "Admins can manage agency-host relationships" ON public.agency_hosts USING (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "Admins can manage all agencies" ON public.agencies;
CREATE POLICY "Admins can manage all agencies" ON public.agencies USING (public.is_admin(auth.uid()));
DROP POLICY IF EXISTS "Admins can manage app settings" ON public.app_settings;
CREATE POLICY "Admins can manage app settings" ON public.app_settings USING (public.is_admin(auth.uid()));