DROP VIEW IF EXISTS public.profiles_public;
CREATE VIEW public.profiles_public AS
SELECT
  p.id,
  p.username,
  p.display_name,
  p.bio,
  p.avatar_url,
  p.cover_url,
  p.country_code,
  p.country_name,
  p.country_flag,
  p.age,
  p.gender,
  p.is_online,
  p.is_verified,
  p.last_seen_at,
  p.last_seen,
  p.last_active_at,
  p.is_host,
  p.host_status,
  p.host_level,
  p.host_availability,
  p.is_face_verified,
  p.face_verification_status,
  p.face_verified_at,
  p.host_verified_at,
  p.verification_type,
  p.agency_id,
  p.is_agency_owner,
  p.is_in_call,
  p.call_rate_per_minute,
  p.total_call_minutes,
  p.total_calls_received,
  p.user_level,
  p.max_user_level,
  p.tags,
  CASE WHEN COALESCE(p.hide_location,false) THEN NULL ELSE p.city END   AS city,
  CASE WHEN COALESCE(p.hide_location,false) THEN NULL ELSE p.region END AS region,
  p.hide_location,
  p.frame_id,
  p.equipped_frame_id,
  p.equipped_entrance_id,
  p.equipped_bubble_id,
  p.equipped_vehicle_id,
  p.equipped_medal_id,
  p.equipped_noble_card_id,
  p.equipped_entry_banner_id,
  p.equipped_entry_name_bar_id,
  p.current_vip_tier_id,
  p.vip_tier,
  p.vip_expires_at,
  p.weekly_earnings,
  p.total_earnings,
  p.profile_photo_url,
  p.host_photos,
  p.app_uid,
  p.created_at
FROM public.profiles p
WHERE COALESCE(p.is_banned,false) = false
  AND COALESCE(p.is_deleted,false) = false;

GRANT SELECT ON public.profiles_public TO authenticated;
GRANT SELECT ON public.profiles_public TO anon;
COMMENT ON VIEW public.profiles_public IS 'Public-safe profile view. Hides coins/beans/blocked_reason/IP/device. Masks city/region when hide_location=true. Excludes banned/deleted users.';